project:
  type: website

website:
  page-navigation: true
  title: "STA 310 - Spring 2024"
  description: "Homepage for STA 310: Generalized Linear Models at Duke University, Spring 2024"
  site-url: https://sta310-sp24.netlify.app

  repo-url: https://github.com/sta310-sp24/website
  repo-actions: [edit, issue]
  
  page-footer:
    background: "#4187aa"
    left: |
      &copy; Copyright 2024, Maria Tackett
    right: |
      This site is built with [Quarto](https://quarto.org/)

  sidebar:
    background: "#4187aa"
    logo: "images/logo.png"
    align: center
    tools: 
      - icon: github
        href: https://github.com/sta310-sp24
        text: "GitHub organization"
      - icon: person-fill
        href: https://sakai.duke.edu/portal/site/f2e8b7dc-61e6-4431-9b5c-29f8411ee5db
        text: "Canvas"
      - icon: person-fill
        href: https://www.gradescope.com/courses/584312
        text: "Gradescope"
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - section: Course information 
        contents: 
        - href: course-overview.qmd
          text: Overview
        - href: syllabus.qmd
          text: Syllabus
        - href: index.qmd
          text: Schedule
        - href: support.qmd
          text: Support
        - href: computing.qmd
          text: Computing
        - href: links.qmd
          text: Useful links
      - section: Homework 
        contents: 
          - href: hw/hw-01.qmd
            text: HW 01
          - href: hw/hw-02.qmd
            text: HW 02
          - href: hw/hw-03.qmd
            text: HW 03
          - href: hw/hw-04.qmd
            text: HW 04
          - href: hw/hw-05.qmd
            text: HW 05
          - href: hw/hw-06.qmd
            text: HW 06
      - section: Projects
        contents:
        - href: projects/project-01.qmd
          text: Project 01
        - href: projects/project-02.qmd
          text: Project 02
        - href: projects/final-project.qmd
          text: Final Project
        - href: project-tips.qmd
          text: Tips + resources

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    mainfont: "Open Sans"
    code-copy: true
    code-overflow: wrap
    toc: true

execute:
  freeze: auto

editor: visual    
    



