---
title: "Course overview"
navbar: false
---

# Overview

STA 310 builds upon the content in STA 210: Regression Analysis. In STA 310 students will be introduced to generalized linear models (GLMs), a broad modeling framework that includes linear and logistic models, among others. Students will learn the basic theory of GLMs and how they can used to model a variety of response variables with non-normal distributions. Students will also learn an extension of GLMs that can be applied to modeling data with correlated observations, such as data with repeated measures.

# Class meetings

|             |           |               |                       |
|-------------|-----------|---------------|-----------------------|
| **Lecture** | Mon & Wed | 3:05 - 4:20pm | Physics 205           |
| **Lab 01**  | Thu       | 3:05 - 4:20pm | Perkins 071 (Link #5) |
| **Lab 02**  | Thu       | 4:40 - 5:55pm | Perkins 071 (Link #5) |

# Teaching team

### Instructor

[Maria Tackett](https://www2.stat.duke.edu/~mt324) is an Assistant Professor of the Practice in the Department of Statistical Science at Duke University. Her work focuses on understanding how active learning strategies can be used to promote engagement and student motivation in undergraduate statistics courses. She also studies how classroom practices in introductory math and statistics courses impact students' sense of community, self-efficacy, and learning outcomes.

+----------------------+---------------+
| Office hours         | Location      |
+======================+===============+
| Mon 10:30 - 11:30am  | Old Chem 118B |
|                      |               |
| Wed 1:30 - 2:30pm    |               |
+----------------------+---------------+
| *or by appointment.* |               |
+----------------------+---------------+

## Teaching assistant

The teaching assistant for this course is [Hun Kang](https://www.linkedin.com/in/gyeonghunkang). He is a PhD student in Statistics, and his research interests include scalable model selection, Bayesian nonparametrics and correlated and longitudinal data analysis.

|             | Location      |
|-------------|---------------|
| Tue 3 - 5pm | Old Chem 203B |
