---
title: "Statistics Experience"
subtitle: "Due: Mon, Nov 20 at 11:59pm "
editor: visual
---

The world of statistics and data science is vast and continually growing! The goal of the statistics experience assignments is to help you engage with the statistics and data science communities outside of the classroom.

You may submit the statistics experience assignment anytime between now and the deadline.

Each experience has two parts:

1️⃣ Have a statistics experience.

2️⃣ Make a slide reflecting on your experience.

**You must complete both parts to receive credit. The statistics experience will count as a homework grade.**

## Part 1: Experience statistics outside of the classroom

Complete an activity in one of the categories below. Under each category are suggested activities. You do not have to do one these suggested activities. You are welcome to find other activities as long as they are related to statistics/data science and they fit in one of the six categories. If there is an activity you'd like to do but you're not sure if it qualifies for the statistics experience, just ask!

### Category 1: Attend a talk or conference

Attend an talk, panel, or conference related to statistics or data science. If you are attending a single talk or panel, it must be *at least 30 minutes* to count towards the statistics experience. The event can be in-person or online.

### Category 2: Talk with a statistician/ data scientist

Talk with someone who uses statistics in their daily work. This could include a professor, professional in industry, graduate student, etc.

### Category 3: Listen to a podcast / watch video

Listen to a podcast or watch a video about statistics and data science. The podcast or video must be *at least 30 minutes* to count towards the statistics experience. A few suggestions are below:

-   [Stats + Stories Podcast](https://statsandstories.net/)
-   [Causal Inference Podcast](https://casualinfer.libsyn.com/)
-   [FiveThirtyEight Model Talk](https://fivethirtyeight.com/tag/model-talk/)
-   rstudio::conf talks
    -   [2022 conference](https://www.rstudio.com/conference/)

    -   [2021 conference](https://www.rstudio.com/resources/rstudioglobal-2021/)

    -   [2020 conference](https://www.rstudio.com/resources/rstudioconf-2020/)

This list is not exhaustive. You may listen to other podcasts or watch other statistics/data science videos not included on this list. Ask Professor Tackett if you are unsure whether a particular podcast or video will count towards the statistics experience.

### Category 4: Participate in a data science competition or challenge

Participate in a statistics or data science competition. You can participate individually or with a team.

### Category 5: Read a book on statistics/data science

There are *a lot* of books about statistics, data science, and related topics. A few suggestions are below. If you decide to read a book that isn't on this list, ask Professor Tackett to make sure it counts toward the experience. Many of these books are available through Duke library.

-   *Weapons of Math Destruction* by Cathy O'Neil
-   *How Charts Lie: Getting Smarter about Visual Information* by Alberto Cairo
-   *The Theory that Would Not Die* by Sharon Bertsch McGrayne
-   *The Art of Statistics: How to learn from data* by David Spiegelhalter
-   *The Signal and the Noise: Why so many predictions fail - but some don't* by Nate Silver
-   [List of books about data science ethics](https://teachdatascience.com/bookclub/)

This list is not exhaustive.

### Category 6: TidyTuesday

You may also participate in a TidyTuesday challenge. New data sets are announced on Monday afternoons.You can find more information about TidyTuesday and see the data in the [TidyTuesday GitHub repo](https://github.com/rfordatascience/tidytuesday).

A few guidelines:

✅ Create a GitHub repo for your TidyTuesday submission. Your repo should include

-   The R Markdown file with all the code needed to reproduce your visualization.
-   A README that includes an image of your final visualization and a short summary (\~ 1 paragraph) about your visualization.

✅ The visualization should include features or customization that are beyond what we've done in class .

✅ Include the link to your GitHub repo in the slide summarizing your experience.

### Category 7: CURV - connecting, uplifting, and recognizing voices

[CURV](https://hardin47.github.io/CURV/) is a project by Dr. Jo Hardin at Pomona College to highlight statisticians and data scientists from groups who have been historically marginalized in the discipline. We will highlight some of the scholars in the CURV data base through the "Statistician of the Day" during lecture each week.

There are two options for this statistics experience:

1️⃣. Present the Statistician of the Day. Learn about one of the scholars in the CURV data base and present what you learn in class.

A few guidelines:

-   Let Professor Tackett know at least one week in advance of when you'd like to present a Statistician of the Day. They will take place at the beginning of lectures on Mondays.

-   Create 1 - 2 slides about the scholar.

-   Present at the beginning of lecture for both lectures. If you are unable to attend the beginning of both lectures, you can present in-person during your lecture period and provide a short video for the other lecture period.

2️⃣ Contribute to the CURV data base. If there is a scholar you would like to suggest for the data base, submit your suggestion as an issue or pull request on the [CURV GitHub repo](https://github.com/hardin47/CURV/) and create a sample CURV page.

A few guidelines:

✅ Create a draft of the CURV page for your suggested scholar. For reference, [click here](https://hardin47.github.io/CURV/scholars/dubois.html) for the CURV page for W.E.B. Du Bois. The page must be created in a Quarto document.

::: callout-tip
You can find the Quarto documents for current scholars in the data base in the CURV GitHub repo. You can use one of these as a template to format your page.
:::

✅ Make a pull request to the CURV GitHub repo to add the `.qmd` file for your suggested scholar, [**OR**]{.underline} open an issue with a link to the `.qmd` file for your suggested scholar. You can ask a member of the teaching team if you have questions about how to do this.

✅ Include the URL to your pull request or issue in your one-slide reflection.

## Part 2: Reflect on your experience

Make one slide summarizing and reflecting on your experience. Submit the slide as a PDF on Gradescope.

Include the following on your slide:

-   Name and brief description of the event/podcast/competition/etc.
-   Something you found new, interesting, or unexpected
-   How the event/podcast/competition/etc. connects to something we've done in class.
-   Citation or link to web page for event/competition/etc.

[Click here](https://docs.google.com/presentation/d/1Ua7rmAQn8FaRLxJpxaRvOZfBLIlEjYVxugEaaTcIjMQ/edit?usp=sharing) to see a template to help you get started on your slide. Your slide does not have to follow this exact format; it just needs to include the information mentioned above and be easily readable (i.e. use a reasonable font size!). Creativity is encouraged!

## Submission

Submit the reflection as a PDF under the **Statistics Experience** assignment on Gradescope by **Mon, Nov 20 at 11:59pm.** Standard homework late policy applies.
