---
title: "Exam 01 review"
author: "Prof. Maria Tackett"
date: "2023-10-02"
date-format: "MMM DD, YYYY"
footer: "[🔗 STA 210 - Fall 2023 -  Schedule](https://sta210-fa23.netlify.app/schedule)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: false
    incremental: false 
    chalkboard: true
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
bibliography: references.bib
---

## Announcements {.midi}

-   HW 02 due TODAY at 11:59pm.
-   All lecture recordings available until Wed, Oct 4 at 9am.
    -   [Click here](https://docs.google.com/spreadsheets/d/1dUD4SOpM79BL2kdvue9I2TP-ibcdxfpOIkHkMreYx64/edit?usp=sharing) for link to videos. You can also find the link in the navigation bar of the course website.
-   No labs this week
-   No office hours Wednesday - Friday
-   Ed Discussion archived (no new posts) Wednesday - Friday

## Exam 01 {.midi}

-   15% of final course grade

-   50 points total

    -   in-class: 40 points
    -   take-home: 10 points

-   In-class: 75 minutes during Wed, Oct 4 lecture

-   Take-home:

    -   Released: Wed, Oct 4 \~ 3pm
    -   Due: Fri, Oct 6 at 11:59pm
    -   Similar in format to a lab/ HW

-   If you miss any part of the exam for an excused absence (with academic dean's note), then Exam 02 score will be counted twice

## Content: Weeks 1 - 5

::: columns
::: {.column width="50%"}
-   Exploratory data analysis

-   Fitting and interpreting simple linear regression models

-   Statistical models and regression equations

-   Simulation-based inference

-   Mathematical models for inference
:::

::: {.column width="50%"}
-   Prediction

-   Model conditions

-   Model evaluation

-   Basics of multiple linear regression
:::
:::

## Outline of in-class portion {.midi}

-   Closed-book, closed-note.

-   10 questions, some with multiple parts

-   Question types:

    -   Multiple choice
    -   Short answer (no more than 3 sentences)
    -   True/ False.
        -   If false, write 1 - 2 sentence justification about why it is false.
    -   Evaluate a response.

-   Last page (front and back) will have analysis output.

-   Just need a pencil. No calculator permitted on exam.

# Application exercise

::: appex
📋 [sta210-fa23.netlify.app/ae/ae-08-exam-01-review](https://sta210-fa23.netlify.app/ae/ae-08-exam-01-review.html)
:::

-   Sit with your lab group.

-   Put your group's response to your assigned exercise on Ed Discussion.

    -   Section 001: [edstem.org/us/courses/44523/discussion/3542094](https://edstem.org/us/courses/44523/discussion/3542094)

    -   Section 002: [edstem.org/us/courses/44523/discussion/3542095](https://edstem.org/us/courses/44523/discussion/3542095)
