---
title: "Logistic Regression: Model comparison"
author: "Prof. Maria Tackett"
date: "2022-11-14"
date-format: "MMM DD, YYYY"
footer: "[🔗 Week 12](https://sta210-fa22.netlify.app/weeks/week-12.html)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
execute:
  freeze: auto
  echo: true
  warning: false
  message: false
knitr:
  opts_chunk: 
    R.options:      
    width: 200
---

```{r}
#| include: false

# figure options
knitr::opts_chunk$set(
  fig.width = 8, fig.asp = 0.618, out.width = "90%",
  fig.retina = 3, dpi = 300, fig.align = "center"
)

library(countdown)
```

## Announcements

-   HW 04 due Mon, Nov 21, 11:59pm (released later today)

-   Upcoming dates:

    -   Project deadlines (see next slide)

    -   Exam 02: Mon, Dec 05, 7pm - Thu, Dec 08, 12pm (noon)

    -   [Statistics experience](../hw/stats-experience.html) due Fri, Dec 09, 11:59pm

-   See [Week 12](../weeks/week-12.html) activities

## Project

-   Proposals
    -   Feedback is posted throughout document, so scroll through all pages of the document for comments (not just the comments section of the rubric)

    -   Recall: The final project grade is the sum of the points on each part
-   Coming up next:
    -   Project meetings (optional): Mon, Nov 21 (sign up sheet available later this week)

    -   [Round 1 submission (optional)](https://sta210-fa22.netlify.app/project-instructions.html#draft-report) due Tue, Nov 22

    -   Written report due Fri, Dec 09

## Application exercise

::: appex
📋 [AE 14: Logistic Regression - Model Comparison](../ae/ae-14-model-compare.html)
:::

-   Sit with your lab groups.

-   Submit questions and responses on Ed Discussion:

    -   10:15am: [edstem.org/us/courses/26900/discussion/2154489](https://edstem.org/us/courses/26900/discussion/2154489)

    -   3:30pm: [edstem.org/us/courses/26900/discussion/2154491](https://edstem.org/us/courses/26900/discussion/2154491)
