---
title: "Exam 02 review"
author: "Prof. Maria Tackett"
date: "2023-11-29"
date-format: "MMM DD, YYYY"
footer: "[🔗 STA 210 - Fall 2023 -  Schedule](https://sta210-fa23.netlify.app/schedule)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: false
    incremental: false 
    chalkboard: true
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
  warning: false
  message: false
knitr:
  opts_chunk: 
    R.options:      
    width: 200
bibliography: references.bib
---

## Announcements {.small}

-   Due dates
    -   HW 05 due TODAY at 11:59pm
-   Project
    -   (Optional) [Round 1 submission](https://sta210-fa23.netlify.app/project-instructions#round1-submission) due Fri, Dec 01 at 11:59pm
    -   [Presentations](https://sta210-fa23.netlify.app/project-instructions#presentation) in lab Dec 5 & 7
-   Exam 02 dates
    -   In-class: Mon, Dec 4
    -   Take-home: Mon, Dec 4 - Wed, Dec 6
    -   Review: Wed, Nov 29
    -   No Ed Discussion or office hours Dec 4 - 6
-   [Click here](https://docs.google.com/spreadsheets/d/1dUD4SOpM79BL2kdvue9I2TP-ibcdxfpOIkHkMreYx64/edit?usp=sharing) to access lecture recordings. Available until Mon, Dec 04 at 9am
-   Please fill out course evaluations

## Course + TA evaluations 

-   Course and TA evaluations are now available (will receive email about TA evals)

-   If there is at least 80% on the course evaluations [**and**]{.underline} TA evaluations, everyone in the class will get 1 percentage point (i.e. 0.5 out of 50) on Exam 02.

    -   This will be determined separately for the Sections 001 and 002.

## Exam 02 {.midi}

-   15% of final course grade

-   50 points total

    -   in-class: 35 points
    -   take-home: 15 points

-   In-class: 75 minutes during Mon, Dec 4 lecture

-   Take-home:

    -   Released: Mon, Dec 4 \~ 3pm
    -   Due: Wed, Oct 6 at 11:59pm
    -   Similar in format to a lab/ HW

## Content: Weeks 5 - 14 {.midi}

::: columns
::: {.column width="50%"}
-   Fitting, interpreting, comparing, and evaluating multiple linear regression models

-   Feature engineering + model workflow using tidymodels

-   Cross validation

-   Inference for multiple linear regression

-   Probabilities, odds, and odds ratios
:::

::: {.column width="50%"}
-   Fitting, interpreting, comparing, and evaluating logistic regression models

```{=html}
<!-- -->
```
-   Using logistic regression models for prediction and classification

-   Fitting, interpreting, comparing, and evaluating multinomial logistic regression models

-   Using multinomial logistic regression models for prediction and classification
:::
:::

## Outline of in-class portion {.midi}

-   Closed-book, closed-note.

-   8-10 questions, some with multiple parts

-   Question types:

    -   Multiple choice
    -   Short answer (no more than 3 sentences)
    -   True/ False.
        -   If false, write 1 - 2 sentence justification about why it is false. Must get justification correct to receive credit.
    -   Evaluate a response.

-   Last page will have analysis output.

-   Just need a pencil or pen. No calculator permitted on exam.

# Application exercise

::: appex
📋 [sta210-fa23.netlify.app/ae/ae-17-exam-02-review](https://sta210-fa23.netlify.app/ae/ae-17-exam-02-review.html)
:::
