---
title: "Exam 02 review"
author: "Prof. Maria Tackett"
date: "2022-12-05"
date-format: "MMM DD, YYYY"
footer: "[🔗 Week 15](https://sta210-fa22.netlify.app/weeks/week-15.html)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
execute:
  freeze: auto
  echo: true
  warning: false
  message: false
knitr:
  opts_chunk: 
    R.options:      
    width: 200
---

```{r setup}
#| include: false

library(countdown)

knitr::opts_chunk$set(
  fig.width = 10,
  fig.asp = 0.618,
  fig.retina = 3,
  dpi = 300,
  fig.align = "center"
)
```

## Announcements {.midi}

-   Due dates

    -   Team Feedback #2 due Tue, Dec 06, 11:59pm (check for email from Teammates)
    -   [Statistics experience](../hw/stats-experience.html) due Fri, Dec 09, 11:59pm
    -   Project written report due Fri, Dec 09, 11:59pm

-   Exam 02: Mon, Dec 05 (evening) - Thu, Dec 08, 12pm (noon)

    -   [Click here](https://duke.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=3abb0b6f-0db5-4d55-84f2-aefd0140874b) for lecture recordings - available until Dec 05, 11:59pm

## Course evals

-   Course and TA evaluations are now available (check email for TA evaluations).

-   If there is at least 80% on the course evaluations <u>**and**</u> TA evaluations, everyone in the class will get 1 point on Exam 02.

    -   This will be determined separately for the Sections 001 and 002.

## Project

-   Written report submission: due Fri, Dec 09, 11:59pm (accepted until Sun, Dec 11, 11:59pm)

    -   Submit by pushing to your GitHub repo. There is <u> no</u> submission on Gradescope

-   Next steps:

    -   Video + slides: due Wed, Dec 14, 11:59pm

    -   Repo organization due Wed, Dec 14, 11:59pm

    -   Video comments: due Fri, Dec 16, 11:59pm

-   Link: [sta210-fa22.netlify.app/project-instructions](https://sta210-fa22.netlify.app/project-instructions.html)

## Exam instructions {.midi}

::: incremental
-   The exam is an individual assignment. Everything in your repository is for your eyes only.

-   You may not collaborate or communicate anything about this exam to anyone except the instructor. For example, you may not communicate with other students, the TAs, or post/solicit help on the internet, email or via any other method of communication.

-   The exam is open-book, open-note, so you may use any materials from class as you take the exam.

-   No TA office hours will be held during the exam. You may not email the TAs questions about the exam.

-   Ed Discussion is <u>**only**</u> for questions about the final project.

-   Email Prof. Tackett with "STA 210 Exam" in the subject line if you have questions
:::

## Exam 02 logistics {.midi}

::: incremental
-   Released today \~ 7pm (will receive email) and due Thu, Dec 08, 12pm (noon)
-   Exam instructions can be found in the README of the `exam-02` Repo
    -   Exercise prompts will be in `exam-02.qmd`
-   Covers everything we've done Weeks 06 - 13
-   Office hours during exam:
    -   Wed, Dec 07 during your class period (Zoom link in Sakai)

    -   Prof. Tackett office hours

        -   Mon, 1 - 2pm

        -   Thu, 10 - 11am
:::

## Assessment criteria {.midi}

-   You can identify the correct approach, analysis method, and/or inferential results required to answer the question.
-   You understand the correct conditions and diagnostics needed to determine whether the conclusions drawn from the model will be reliable
-   You can write results and conclusions in a meaningful way that can be understood by a general audience (think a business or research partner)
-   You can produce a report that is suitable for a professional audience (e.g., narrative is written in complete sentences, all graphs have proper titles and axis labels, there is not extraneous output, all LaTex is rendered)
-   You can conduct the analysis using a reproducible data analysis workflow that incorporates version control

# Application Exercise

::: appex
📋 [AE 16: Exam 02 Review](https://sta210-fa22.netlify.app/ae/ae-16-exam-02-review.html)
:::

-   Sit with your lab group
