---
title: "Lab 04"
subtitle: "Alumni jobs + Collaborative workflows"
author: "Sep 26 & 28, 2023"
footer: "[🔗 STA 210 - Fall 2023 -  Schedule](https://sta210-fa23.netlify.app/schedule)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: false
    incremental: false 
    chalkboard: true
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
bibliography: references.bib
---

# Welcome

## Goals

-   Meet your team!
-   Team agreement
-   Lab 04: Alumni jobs

## Meet your team!

-   [**Click here**](https://prodduke-my.sharepoint.com/:x:/g/personal/mt324_duke_edu/EYSH_1f6JnxClPeTx0PA6HgBLJLDwULnKRFboL_WTSv4dw?e=T5lze5) to find your team.

-   Sit with your team.

## Team name + agreement

-   Come up with a team name. You can't have the same name as another group in the class, so be creative!

    -   Your TA will get your team name by the end of lab.

-   Fill out the team agreement. The goals of the agreement are to...

    -   Gain a common understanding of the team's goals and expectations for collaboration
    -   Make a plan for team communication
    -   Make a plan for working outside of lab

## Team workflow

-   Only <u>**one**</u> team member should type at a time. There are markers in today's lab to help you determine whose turn it is to type.

    -   Every team member should still be engaged in discussion for all questions, even if it's not your turn type.

-   Don't forget to **pull** to get your teammates' updates before making changes to the `.qmd` file.

    ::: callout-important
    **Only one submission per team on Gradescope. Read the submission instructions carefully!**
    :::

## Team workflow, in action

-   Complete the "Workflow: Using Git and GitHub as a team" section of the lab in your teams.
-   Raise your hand if you have any questions about the workflow.

```{r}
#| echo: false
countdown::countdown(minutes = 5, font_size = "2em")
```

## Tips for working on a team {.midi}

-   Do not pressure each other to finish early; use the time wisely to really learn the material and produce a quality report.

-   The labs are structured to help you learn the steps of a data analysis. Do not split up the lab among the team members; work on it together in its entirety.

-   Everyone has something to contribute! Use the lab groups as an opportunity to share ideas and learn from each other.
