---
title: "Lab 03"
subtitle: "Inference for Simple Linear Regression using Mathematical Models"
author: "Sep 19 & 21"
footer: "[🔗 STA 210 - Fall 2023 -  Schedule](https://sta210-fa23.netlify.app/schedule)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: false
    incremental: false 
    chalkboard: true
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
bibliography: references.bib
---

## Reminders {.midi}

Make sure to do the following as you complete the assignment:

-   Write all narrative in complete sentences.

-   Use informative axis titles and labels on all graphs.

-   Implement version control in your reproducible workflow.

    -   Throughout the assignment periodically **render** your Quarto document to produce the updated PDF, **commit** the changes in the Git pane, and **push** the updated files to GitHub.

    -   Benchmark: Push changes to GitHub at least three times as you work on the assignment.

## Today's lab

-   Focused on mathematical inference for simple linear regression and checking model conditions.

    -   We will talk about model conditions in the September 20 lecture.

-   Remember to mark all pages in your Gradescope submission. The first page should be marked for the "Workflow & formatting" section.

-   Use lectures and application exercises as reference as you complete the lab.\
