---
title: "Lab 05"
subtitle: "Feature engineering + model comparison"
author: "Oct 10 & 12"
footer: "[🔗 STA 210 - Fall 2023 -  Schedule](https://sta210-fa23.netlify.app/schedule)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: false
    incremental: false 
    chalkboard: true
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
bibliography: references.bib
---

# Welcome

## Team workflow

-   Only <u>**one**</u> team member should type at a time. There are no markers in today's lab, but you should use a similar workflow as Lab 04.

    -   Every team member should still be engaged in discussion for all questions, even if it's not your turn type.

-   Don't forget to **pull** to get your teammates' updates before making changes to the `.qmd` file.

    ::: callout-important
    **Only one submission per team on Gradescope. Carefully read the submission instructions at the end of the lab instructions.**
    :::

## Tips for working on a team {.midi}

-   Do not pressure each other to finish early; use the time wisely to really learn the material and produce a quality report.

-   The labs are structured to help you learn the steps of a data analysis. Do not split up the lab among the team members; work on it together in its entirety.

-   Everyone has something to contribute! Use the lab groups as an opportunity to share ideas and learn from each other.

## STA 210 Mid Semester Survey

Please take a few minutes to complete the STA 210 Mid Semester Survey.\
\
[Click here](https://duke.qualtrics.com/jfe/form/SV_86XWKdUFjvStYmW) to access the survey.

## Resources for Lab 04 {.midi}

-   Lecture notes:

    -   [Feature engineering](https://sta210-fa23.netlify.app/slides/11-feature-engineering.html#/title-slide)
    -   [Feature engineering: Model workflow](https://sta210-fa23.netlify.app/slides/12-feature-engineering-pt2.html#/title-slide)

-   [Recipes package function reference](https://recipes.tidymodels.org/reference/index.html)

-   Tidy Modeling in R - [Chapter 8: Feature engineering with recipes](https://www.tmwr.org/recipes.html)
