{
  "hash": "6b784b086996c9d08e99ba48193a1a7a",
  "result": {
    "markdown": "---\ntitle: \"SLR: Fitting models in R with tidymodels\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"2022-09-05\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 Week 02](https://sta210-fa22.netlify.app/weeks/week-02.html)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\n---\n\n\n\n## Announcements\n\n-   No office hours today. Office hours start Tuesday, September 6. [Click here](https://docs.google.com/spreadsheets/d/1Ay1GxqU2HDpFwnNLZxv0baIAa1lJwUVdtvmprPdkefk/edit?usp=sharing) for full schedule\n\n-   Check your email for an email to join the course GitHub organization. You will receive one by Tuesday, September 6.\n\n-   See [Week 02](https://sta210-fa22.netlify.app/weeks/week-02.html) for this week's activities.\n\n## Topics\n\n-   Introduce the computing toolkit - RStudio and GitHub\n-   Use tidymodels to fit and summarize regression models in R\n-   Complete an application exercise on exploratory data analysis and modeling\n\n## Computational setup\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)       # for data wrangling\nlibrary(tidymodels)      # for modeling\nlibrary(fivethirtyeight) # for the fandango dataset\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_minimal(base_size = 16))\n\n# set default figure parameters for knitr\nknitr::opts_chunk$set(\n  fig.width = 8,\n  fig.asp = 0.618,\n  fig.retina = 3,\n  dpi = 300,\n  out.width = \"80%\"\n)\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n\n# Computing toolkit\n\n## Reproducibility checklist\n\n::: question\nWhat does it mean for an analysis to be reproducible?\n:::\n\n. . .\n\n**Near term goals**:\n\n✔️ Are the tables and figures reproducible from the code and data?\n\n✔️ Does the code actually do what you think it does?\n\n✔️ In addition to what was done, is it clear *why* it was done?\n\n. . .\n\n**Long term goals**:\n\n✔️ Can the code be used for other data?\n\n✔️ Can you extend the code to do other things?\n\n## Toolkit\n\n-   **Scriptability** $\\rightarrow$ R\n\n-   **Literate programming** (code, narrative, output in one place) $\\rightarrow$ Quarto\n\n-   **Version control** $\\rightarrow$ Git / GitHub\n\n    -   *More on this in this week's lab*\n\n## What are R and RStudio?\n\n-   R is a statistical programming language\n\n-   RStudio is a convenient interface for R (an integrated development environment, IDE)\n\n![](images/03/r_vs_rstudio_1.png){fig-align=\"center\"}\n\n::: footnote\nSource: [Modern Dive](https://moderndive.com/1-getting-started.html)\n:::\n\n------------------------------------------------------------------------\n\n## RStudio IDE\n\n![](images/03/rstudio-panes.png){fig-align=\"center\"}\n\n------------------------------------------------------------------------\n\n## Quarto\n\n-   Fully reproducible reports -- the analysis is run from the beginning each time you render\n\n-   Code goes in chunks and narrative goes outside of chunks\n\n-   Visual editor to make document editing experience similar to a word processor (Google docs, Word, Pages, etc.)\n\n## Quarto\n\n![](images/03/quarto.png){fig-align=\"center\"}\n\n## How will we use Quarto?\n\n-   Every application exercise and assignment is written in a Quarto document\n\n-   You'll have a template Quarto document to start with\n\n-   The amount of scaffolding in the template will decrease over the semester\n\n## Application exercise\n\n::: appex\n📋 [github.com/sta210-fa22/ae-02-bikeshare](https://github.com/sta210-fa22/ae-02-bikeshare)\n:::\n\n# Using R for SLR\n\n## Recap of last lecture {.smaller}\n\n<div>\n\n-   Used simple linear regression to describe the relationship between a quantitative predictor and quantitative outcome variable.\n\n-   Used the least squares method to estimate the slope and intercept.\n\n-   We interpreted the slope and intercept.\n\n    <div>\n\n    -   **Slope:** For every one unit increase in $x$, we expect y to be higher/lower by $\\hat{\\beta}_1$ units, on average.\n    -   **Intercept:** If $x$ is 0, then we expect $y$ to be $\\hat{\\beta}_0$ units.\n\n    </div>\n\n-   Predicted the response given a value of the predictor variable.\n\n-   Defined extrapolation and why we should avoid it.\n\n</div>\n\n# Data\n\n## Movie ratings\n\n::: columns\n::: {.column width=\"70%\"}\n-   Data behind the FiveThirtyEight story [*Be Suspicious Of Online Movie Ratings, Especially Fandango's*](%22Be%20Suspicious%20Of%20Online%20Movie%20Ratings,%20Especially%20Fandango's%22)\n-   In the **fivethirtyeight** package: [`fandango`](https://fivethirtyeight-r.netlify.app/reference/fandango.html)\n-   Contains every film that has at least 30 fan reviews on Fandango, an IMDb score, Rotten Tomatoes critic and user ratings, and Metacritic critic and user scores\n:::\n\n::: {.column width=\"30%\"}\n![](images/03/fandango.png){fig-align=\"center\" width=\"200\"}\n\n![](images/03/imdb.png){fig-align=\"center\" width=\"200\"}\n\n![](images/03/rotten-tomatoes.png){fig-align=\"center\" width=\"200\"}\n\n![](images/03/metacritic.png){fig-align=\"center\" width=\"200\"}\n:::\n:::\n\n## Data prep\n\n-   Rename Rotten Tomatoes columns as `critics` and `audience`\n-   Rename the dataset as `movie_scores`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_scores <- fandango |>\n  rename(\n    critics = rottentomatoes, \n    audience = rottentomatoes_user\n  )\n```\n:::\n\n\n\n------------------------------------------------------------------------\n\n$$\n\\widehat{\\text{audience}} = 32.3142 + 0.5187 \\times \\text{critics}\n$$\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](03-slr-tidymodels_files/figure-html/unnamed-chunk-1-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## tidymodels\n\n::: midi\nThe **tidymodels** framework is a collection of packages for modeling and machine learning using tidyverse principles.\n:::\n\n. . .\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidymodels)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ────────────────────────────────────── tidymodels 1.1.0 ──\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ broom        1.0.5     ✔ rsample      1.1.1\n✔ dials        1.2.0     ✔ tune         1.1.1\n✔ infer        1.0.4     ✔ workflows    1.1.3\n✔ modeldata    1.1.0     ✔ workflowsets 1.0.1\n✔ parsnip      1.1.0     ✔ yardstick    1.2.0\n✔ recipes      1.0.6     \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──\n✖ scales::discard() masks purrr::discard()\n✖ dplyr::filter()   masks stats::filter()\n✖ recipes::fixed()  masks stringr::fixed()\n✖ dplyr::lag()      masks stats::lag()\n✖ yardstick::spec() masks readr::spec()\n✖ recipes::step()   masks stats::step()\n• Use suppressPackageStartupMessages() to eliminate package startup messages\n```\n:::\n:::\n\n\n\n## Why tidymodels?\n\n-   Consistent syntax for different model types (linear, logistic, random forest, Bayesian, etc.)\n-   Streamline modeling workflow\n    -   Split data into train and test sets\n    -   Transform and create new variables\n    -   Assess model performance\n    -   Use model for prediction and inference\n\n# Fitting the model\n\n## Step 1: Specify model\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear Regression Model Specification (regression)\n\nComputational engine: lm \n```\n:::\n:::\n\n\n\n## Step 2: **Set model fitting *engine***\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2\"}\nlinear_reg() |>\n  set_engine(\"lm\") # lm: linear model\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear Regression Model Specification (regression)\n\nComputational engine: lm \n```\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n### Step 3: Fit model & estimate parameters\n\nusing **formula syntax**\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|3\"}\nlinear_reg() |>\n  set_engine(\"lm\") |>\n  fit(audience ~ critics, data = movie_scores)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nparsnip model object\n\n\nCall:\nstats::lm(formula = audience ~ critics, data = data)\n\nCoefficients:\n(Intercept)      critics  \n    32.3155       0.5187  \n```\n:::\n:::\n\n\n\n## A closer look at model output\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_fit <- linear_reg() |>\n  set_engine(\"lm\") |>\n  fit(audience ~ critics, data = movie_scores)\n\nmovie_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nparsnip model object\n\n\nCall:\nstats::lm(formula = audience ~ critics, data = data)\n\nCoefficients:\n(Intercept)      critics  \n    32.3155       0.5187  \n```\n:::\n:::\n\n\n\n$$\\widehat{\\text{audience}} = 32.3155 + 0.5187 \\times \\text{critics}$$\n\n. . .\n\n::: small\n**Note:** The intercept is off by a tiny bit from the hand-calculated intercept, this is likely just due to rounding in the hand calculation.\n:::\n\n## The regression output\n\nWe'll focus on the first column for now...\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|4\"}\nlinear_reg() |>\n  set_engine(\"lm\") |>\n  fit(audience ~ critics, data = movie_scores) |>\n  tidy() \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   32.3      2.34        13.8 4.03e-28\n2 critics        0.519    0.0345      15.0 2.70e-31\n```\n:::\n:::\n\n\n\n## Prediction\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2|5\"}\n# create a data frame for a new movie\nnew_movie <- tibble(critics = 70)\n\n# predict the outcome for a new movie\npredict(movie_fit, new_movie)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1  68.6\n```\n:::\n:::\n\n\n\n## Application exercise\n\n::: appex\n📋 [github.com/sta210-fa22/ae-02-bikeshare](https://github.com/sta210-fa22/ae-02-bikeshare)\n\n![Close document tab](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAbElEQVR4Xs2RQQrAMAgEfZgf7W9LAguybljJpR3wEse5JOL3ZObDb4x1loDhHbBOFU6i2Ddnw2KNiXcdAXygJlwE8OFVBHDgKrLgSInN4WMe9iXiqIVsTMjH7z/GhNTEibOxQswcYIWYOR/zAjBJfiXh3jZ6AAAAAElFTkSuQmCC){alt=\"Close document tab\"}\n:::\n\n## Recap\n\n-   Introduced the computing toolkit - RStudio and GitHub\n-   Used tidymodels to fit and summarize regression models in R\n-   Completed an application exercise on exploratory data analysis and modeling\n",
    "supporting": [
      "03-slr-tidymodels_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}