{
  "hash": "2764004fe5a48bdcfb5ad11118a3a723",
  "result": {
    "markdown": "---\ntitle: \"Simple Linear Regression\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"2023-09-06\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 STA 210 - Fall 2023 -  Schedule](https://sta210-fa23.netlify.app/schedule)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false \n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n# Questions?\n\n# Join sta210-fa23 on GitHub\n\n🔗 [github.com/sta210-fa23](https://github.com/sta210-fa23)\n\n------------------------------------------------------------------------\n\n## Topics\n\n::: incremental\n-   Use simple linear regression to describe the relationship between a quantitative predictor and quantitative response variable.\n\n-   Estimate the slope and intercept of the regression line using the least squares method.\n\n-   Interpret the slope and intercept of the regression line.\n\n-   Predict the response given a value of the predictor variable.\n\n-   Use tidymodels to fit and summarize regression models in R.\n:::\n\n## Computation set up\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)       # for data wrangling\nlibrary(tidymodels)      # for modeling\nlibrary(fivethirtyeight) # for the fandango dataset\nlibrary(knitr)          # for formatting tables\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_bw(base_size = 16))\n\n# set default figure parameters for knitr\nknitr::opts_chunk$set(\n  fig.width = 8,\n  fig.asp = 0.618,\n  fig.retina = 3,\n  dpi = 300,\n  out.width = \"80%\"\n)\n```\n:::\n\n\n\n\n\n# Data\n\n## Movie scores\n\n::: columns\n::: {.column width=\"70%\"}\n-   Data behind the FiveThirtyEight story [*Be Suspicious Of Online Movie Ratings*](https://fivethirtyeight.com/features/fandango-movies-ratings/)[*, Especially Fandango's*](%22Be%20Suspicious%20Of%20Online%20Movie%20Ratings,%20Especially%20Fandango's%22)\n-   In the **fivethirtyeight** package: [`fandango`](https://fivethirtyeight-r.netlify.app/reference/fandango.html)\n-   Contains every film released in 2014 and 2015 that has at least 30 fan reviews on Fandango, an IMDb score, Rotten Tomatoes critic and user ratings, and Metacritic critic and user scores\n:::\n\n::: {.column width=\"30%\"}\n![](images/02/fandango.png){fig-alt=\"Fandango logo\" width=\"200\"}\n\n![](images/02/imdb.png){fig-alt=\"IMDB logo\" width=\"200\"}\n\n![](images/02/rotten-tomatoes.png){fig-alt=\"Rotten Tomatoes logo\" width=\"200\"}\n\n![](images/02/metacritic.png){fig-alt=\"Metacritic logo\" width=\"200\"}\n:::\n:::\n\n## Data prep\n\n-   Rename Rotten Tomatoes columns as `critics` and `audience`\n-   Rename the dataset as `movie_scores`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_scores <- fandango |>\n  rename(critics = rottentomatoes, \n         audience = rottentomatoes_user)\n```\n:::\n\n\n\n## Data overview\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(movie_scores)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 146\nColumns: 23\n$ film                       <chr> \"Avengers: Age of Ultron\", \"Cinderella\", \"A…\n$ year                       <dbl> 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2…\n$ critics                    <int> 74, 85, 80, 18, 14, 63, 42, 86, 99, 89, 84,…\n$ audience                   <int> 86, 80, 90, 84, 28, 62, 53, 64, 82, 87, 77,…\n$ metacritic                 <int> 66, 67, 64, 22, 29, 50, 53, 81, 81, 80, 71,…\n$ metacritic_user            <dbl> 7.1, 7.5, 8.1, 4.7, 3.4, 6.8, 7.6, 6.8, 8.8…\n$ imdb                       <dbl> 7.8, 7.1, 7.8, 5.4, 5.1, 7.2, 6.9, 6.5, 7.4…\n$ fandango_stars             <dbl> 5.0, 5.0, 5.0, 5.0, 3.5, 4.5, 4.0, 4.0, 4.5…\n$ fandango_ratingvalue       <dbl> 4.5, 4.5, 4.5, 4.5, 3.0, 4.0, 3.5, 3.5, 4.0…\n$ rt_norm                    <dbl> 3.70, 4.25, 4.00, 0.90, 0.70, 3.15, 2.10, 4…\n$ rt_user_norm               <dbl> 4.30, 4.00, 4.50, 4.20, 1.40, 3.10, 2.65, 3…\n$ metacritic_norm            <dbl> 3.30, 3.35, 3.20, 1.10, 1.45, 2.50, 2.65, 4…\n$ metacritic_user_nom        <dbl> 3.55, 3.75, 4.05, 2.35, 1.70, 3.40, 3.80, 3…\n$ imdb_norm                  <dbl> 3.90, 3.55, 3.90, 2.70, 2.55, 3.60, 3.45, 3…\n$ rt_norm_round              <dbl> 3.5, 4.5, 4.0, 1.0, 0.5, 3.0, 2.0, 4.5, 5.0…\n$ rt_user_norm_round         <dbl> 4.5, 4.0, 4.5, 4.0, 1.5, 3.0, 2.5, 3.0, 4.0…\n$ metacritic_norm_round      <dbl> 3.5, 3.5, 3.0, 1.0, 1.5, 2.5, 2.5, 4.0, 4.0…\n$ metacritic_user_norm_round <dbl> 3.5, 4.0, 4.0, 2.5, 1.5, 3.5, 4.0, 3.5, 4.5…\n$ imdb_norm_round            <dbl> 4.0, 3.5, 4.0, 2.5, 2.5, 3.5, 3.5, 3.5, 3.5…\n$ metacritic_user_vote_count <int> 1330, 249, 627, 31, 88, 34, 17, 124, 62, 54…\n$ imdb_user_vote_count       <int> 271107, 65709, 103660, 3136, 19560, 39373, …\n$ fandango_votes             <int> 14846, 12640, 12055, 1793, 1021, 397, 252, …\n$ fandango_difference        <dbl> 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5…\n```\n:::\n:::\n\n\n\n## Movie scores data\n\nThe data set contains the \"Tomatometer\" score (**`critics`**) and audience score (**`audience`**) for 146 movies rated on rottentomatoes.com.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03-slr-intro_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## Movie ratings data\n\n**Goal**: Fit a line to describe the relationship between the critics score and audience score.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](03-slr-intro_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## Why fit a line?\n\nWe fit a line to accomplish one or both of the following:\n\n. . .\n\n::: {style=\"color: #799100\"}\n**Prediction**\n:::\n\nWhat is the audience score expected to be for an upcoming movie that received 35% from the critics?\\\n\n. . .\n\n::: {style=\"color : #799100\"}\n**Inference**\n:::\n\nIs the critics score a useful predictor of the audience score? By how much is the audience score expected to change for each additional point in the critics score?\\\n\n## Terminology\n\n::: columns\n::: {.column width=\"30%\"}\n-   **Response, *Y***: variable describing the outcome of interest\n\n-   **Predictor, *X***: variable we use to help understand the variability in the response\n:::\n\n::: {.column width=\"70%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](03-slr-intro_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n:::\n:::\n\n## Regression model\n\nA **regression model** is a function that describes the relationship between the response, $Y$, and the predictor, $X$.\n\n\n\n```{=tex}\n\\begin{aligned} Y &= \\color{black}{\\textbf{Model}} + \\text{Error} \\\\[8pt]\n&= \\color{black}{\\mathbf{f(X)}} + \\epsilon \\\\[8pt]\n&= \\color{black}{\\boldsymbol{\\mu_{Y|X}}} + \\epsilon \\end{aligned}\n```\n\n\n## Regression model\n\n::: columns\n::: {.column width=\"30%\"}\n\n\n```{=tex}\n\\begin{aligned} Y &= \\color{purple}{\\textbf{Model}} + \\text{Error} \\\\[8pt]\n&= \\color{purple}{\\mathbf{f(X)}} + \\epsilon \\\\[8pt]\n&= \\color{purple}{\\boldsymbol{\\mu_{Y|X}}} + \\epsilon \\end{aligned}\n```\n\n\n:::\n\n::: {.column width=\"70%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](03-slr-intro_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n:::\n:::\n\n$\\mu_{Y|X}$ is the mean value of $Y$ given a particular value of $X$.\n\n## Regression model\n\n::: columns\n::: {.column width=\"30%\"}\n$$\n\\begin{aligned} Y &= \\color{purple}{\\textbf{Model}} + \\color{blue}{\\textbf{Error}} \\\\[5pt]\n&= \\color{purple}{\\mathbf{f(X)}} + \\color{blue}{\\boldsymbol{\\epsilon}} \\\\[5pt]\n&= \\color{purple}{\\boldsymbol{\\mu_{Y|X}}} + \\color{blue}{\\boldsymbol{\\epsilon}} \\\\[5pt]\n \\end{aligned}\n$$\n:::\n\n::: {.column width=\"70%\"}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](03-slr-intro_files/figure-html/unnamed-chunk-7-1.png){width=80%}\n:::\n:::\n\n\n:::\n:::\n\n# Simple linear regression (SLR)\n\n## SLR: Statistical model\n\nWhen we have a quantitative response, $Y$, and a single quantitative predictor, $X$, we can use a **simple linear regression** model to describe the relationship between $Y$ and $X$. $$\\Large{Y = \\mathbf{\\beta_0 + \\beta_1 X} + \\epsilon}$$\n\n. . .\n\n-   $\\beta_1$: True slope of the relationship between $X$ and $Y$\n-   $\\beta_0$: True intercept of the relationship between $X$ and $Y$\n-   $\\epsilon$: Error\n\n## SLR: Regression equation\n\n$$\\Large{\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 X}$$\n\n-   $\\hat{\\beta}_1$: Estimated slope of the relationship between $X$ and $Y$\n-   $\\hat{\\beta}_0$: Estimated intercept of the relationship between $X$ and $Y$\n-   No error term!\n\n## Choosing values for $\\hat{\\beta}_1$ and $\\hat{\\beta}_0$\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n:::\n\n::: {.cell-output-display}\n![](03-slr-intro_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## Residuals\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](03-slr-intro_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n$$\\text{residual} = \\text{observed} - \\text{predicted} = y_i - \\hat{y}_i$$\n\n## Least squares line\n\n-   The residual for the $i^{th}$ observation is\n\n$$e_i = \\text{observed} - \\text{predicted}\n= y_i - \\hat{y}_i$$\n\n-   The **sum of squared residuals** is\n\n$$e^2_1 + e^2_2 + \\dots + e^2_n$$\n\n-   The **least squares line** is the one that minimizes the sum of squared residuals\n\n\n\n::: {.cell}\n\n:::\n\n\n\n# Slope and intercept\n\n## Properties of least squares regression\n\n::: incremental\n-   The regression line goes through the center of mass point, the coordinates corresponding to average $X$ and average $Y$: $\\hat{\\beta}_0 = \\bar{Y} - \\hat{\\beta}_1\\bar{X}$\n\n-   The slope has the same sign as the correlation coefficient: $\\hat{\\beta}_1 = r \\frac{s_Y}{s_X}$\n\n-   The sum of the residuals is approximately zero: $\\sum_{i = 1}^n e_i \\approx 0$\n\n-   The residuals and $X$ values are uncorrelated\n:::\n\n## Estimating the slope\n\n$$\\large{\\hat{\\beta}_1 = r \\frac{s_Y}{s_X}}$$\n\n::: columns\n::: {.column width=\"50%\"}\n\n\n```{=tex}\n\\begin{aligned} \ns_X &= 30.1688 \\\\\ns_Y &=  20.0244 \\\\\nr &= 0.7814\n\\end{aligned}\n```\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n```{=tex}\n\\begin{aligned}\n\\hat{\\beta}_1 &= 0.7814 \\times \\frac{20.0244}{30.1688} \\\\\n&= 0.5187\\end{aligned}\n```\n\n\n:::\n:::\n\n<br>\n\n::: small\n[Clickhere](https://introregression.netlify.app/98-appendix) for details on deriving the equations for slope and intercept.\n:::\n\n## Estimating the intercept\n\n$$\\large{\\hat{\\beta}_0 = \\bar{Y} - \\hat{\\beta}_1\\bar{X}}$$\n\n::: columns\n::: {.column width=\"50%\"}\n\n\n```{=tex}\n\\begin{aligned}\n&\\bar{x} = 60.8493 \\\\\n&\\bar{y} = 63.8767 \\\\\n&\\hat{\\beta}_1 = 0.5187\n\\end{aligned}\n```\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n```{=tex}\n\\begin{aligned}\\hat{\\beta}_0 &= 63.8767 - 0.5187 \\times 60.8493 \\\\\n&= 32.3142\n\\end{aligned}\n```\n\n\n:::\n:::\n\n<br>\n\n::: small\n[Click here](https://introregression.netlify.app/98-appendix) for details on deriving the equations for slope and intercept.\n:::\n\n## Interpretation\n\n::: appex\n::: midi\nPost your answers to the following questions on Ed Discussion:\n\n-   The slope of the model for predicting audience score from critics score is 0.5187 . Which of the following is the best interpretation of this value?\n\n-   32.3142 is the predicted mean audience score for what type of movies?\n:::\n:::\n\n-   Link for [Section 001 (10:05am lecture)](https://edstem.org/us/courses/44523/discussion/429484)\n\n-   Link for [Section 002 (1:25pm lecture)](https://edstem.org/us/courses/44523/discussion/429493)\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"countdown\" id=\"timer_7c4b83af\" data-update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">03</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n:::\n:::\n\n\n\n## Does it make sense to interpret the intercept?\n\n. . .\n\n✅ **The intercept is meaningful in the context of the data if**\n\n-   the predictor can feasibly take values equal to or near zero, or\n\n-   there are values near zero in the observed data.\n\n. . .\n\n🛑 Otherwise, the intercept may not be meaningful!\n\n# Prediction\n\n## Making a prediction\n\nSuppose that a movie has a critics score of 70. According to this model, what is the movie's predicted audience score?\n\n\n\n```{=tex}\n\\begin{aligned}\n\\widehat{\\text{audience}} &= 32.3142 + 0.5187 \\times \\text{critics} \\\\\n&= 32.3142 + 0.5187 \\times 70 \\\\\n&= 68.6232\n\\end{aligned}\n```\n\n\n# Fitting regression models with tidymodels\n\n## tidymodels\n\n::: midi\nThe **tidymodels** framework is a collection of packages for modeling and machine learning using tidyverse principles.\n:::\n\n. . .\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidymodels)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ────────────────────────────────────── tidymodels 1.1.0 ──\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ broom        1.0.5     ✔ rsample      1.1.1\n✔ dials        1.2.0     ✔ tune         1.1.1\n✔ infer        1.0.4     ✔ workflows    1.1.3\n✔ modeldata    1.1.0     ✔ workflowsets 1.0.1\n✔ parsnip      1.1.0     ✔ yardstick    1.2.0\n✔ recipes      1.0.6     \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──\n✖ scales::discard() masks purrr::discard()\n✖ dplyr::filter()   masks stats::filter()\n✖ recipes::fixed()  masks stringr::fixed()\n✖ dplyr::lag()      masks stats::lag()\n✖ yardstick::spec() masks readr::spec()\n✖ recipes::step()   masks stats::step()\n• Dig deeper into tidy modeling with R at https://www.tmwr.org\n```\n:::\n:::\n\n\n\n## Why tidymodels?\n\n-   Consistent syntax for different model types (linear, logistic, random forest, Bayesian, etc.)\n-   Streamline modeling workflow\n    -   Split data into train and test sets\n    -   Transform and create new variables\n    -   Assess model performance\n    -   Use model for prediction and inference\n\n# Fitting the model\n\n## Step 1: Specify model\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear Regression Model Specification (regression)\n\nComputational engine: lm \n```\n:::\n:::\n\n\n\n## Step 2: **Set model fitting *engine***\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2\"}\nlinear_reg() |>\n  set_engine(\"lm\") # lm: linear model\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear Regression Model Specification (regression)\n\nComputational engine: lm \n```\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n### Step 3: Fit model & estimate parameters\n\nusing **formula syntax**\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|3\"}\nlinear_reg() |>\n  set_engine(\"lm\") |>\n  fit(audience ~ critics, data = movie_scores)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nparsnip model object\n\n\nCall:\nstats::lm(formula = audience ~ critics, data = data)\n\nCoefficients:\n(Intercept)      critics  \n    32.3155       0.5187  \n```\n:::\n:::\n\n\n\n## A closer look at the regression output\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovie_fit <- linear_reg() |>\n  set_engine(\"lm\") |>\n  fit(audience ~ critics, data = movie_scores)\n\nmovie_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nparsnip model object\n\n\nCall:\nstats::lm(formula = audience ~ critics, data = data)\n\nCoefficients:\n(Intercept)      critics  \n    32.3155       0.5187  \n```\n:::\n:::\n\n\n\n$$\\widehat{\\text{audience}} = 32.3155 + 0.5187 \\times \\text{critics}$$\n\n. . .\n\n::: smallest\n**Note:** The intercept is off by a tiny bit from the hand-calculated intercept, this is just due to rounding in the hand calculation.\n:::\n\n## The regression output\n\nWe'll focus on the first column for now...\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|4\"}\nlinear_reg() |>\n  set_engine(\"lm\") |>\n  fit(audience ~ critics, data = movie_scores) |>\n  tidy() \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   32.3      2.34        13.8 4.03e-28\n2 critics        0.519    0.0345      15.0 2.70e-31\n```\n:::\n:::\n\n\n\n## Format output with `kable`\n\nUse the `kable` function from the [knitr](https://yihui.org/knitr/) package to produce a table and specify number of significant digits\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|5\"}\nlinear_reg() |>\n  set_engine(\"lm\") |>\n  fit(audience ~ critics, data = movie_scores) |>\n  tidy() |>\n  kable(digits = 4)\n```\n\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |  32.3155|    2.3425|   13.7953|       0|\n|critics     |   0.5187|    0.0345|   15.0281|       0|\n:::\n:::\n\n\n\n## Prediction\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2|5\"}\n# create a data frame for a new movie\nnew_movie <- tibble(critics = 70)\n\n# predict the outcome for a new movie\npredict(movie_fit, new_movie)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1  68.6\n```\n:::\n:::\n\n\n\n# Application exercise\n\n::: appex\n📋 [sta210-fa23.netlify.app/ae/ae-03-slr.html](https://sta210-fa23.netlify.app/ae/ae-03-slr.html)\n:::\n\n-   Find your `ae-03` repo in the course GitHub organization.\n\n-   If you do not see an `ae-03` repo, [click here](https://classroom.github.com/a/HW9uN-iK) to create one.\n\n# Wrap up\n\n## Recap\n\n::: {.incremental style=\"font-size: 0.85em\"}\n-   Used simple linear regression to describe the relationship between a quantitative predictor and quantitative response variable.\n\n-   Used the least squares method to estimate the slope and intercept.\n\n-   Interpreted the slope and intercept.\n\n    -   **Slope**: For every one unit increase in $x$, we expect y to change by $\\hat{\\beta}_1$ units, on average.\n    -   **Intercept**: If $x$ is 0, then we expect $y$ to be $\\hat{\\beta}_0$ units\n\n-   Predicted the response given a value of the predictor variable.\n\n-   Used tidymodels to fit and summarize regression models in R.\n:::\n",
    "supporting": [
      "03-slr-intro_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/countdown-0.4.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/countdown-0.4.0/countdown.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}