{
  "hash": "3a430728138f4f151f8aaf4084965662",
  "result": {
    "markdown": "---\ntitle: \"Logistic Regression: Model comparison\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"2023-11-08\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 STA 210 - Fall 2023 -  Schedule](https://sta210-fa23.netlify.app/schedule)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false \n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  warning: false\n  message: false\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n\n## Announcements\n\n-   Project draft due in your GitHub repo at **9am** on\n\n    -   November 14 (Tuesday labs)\n    -   November 16 (Thursday labs)\n    -   Will do peer review in lab those days\n\n-   Team Feedback #1 due Friday, November 10 at 11:5pm\n\n    -   Received email from teammates\n\n-   HW 04 due Wednesday, November 15 at 11:59pm\n\n    -   Released later today\n\n## Topics\n\nComparing logistic regression models using\n\n-   Drop-in-deviance test\n\n-   AIC\n\n-   BIC\n\n## Computational setup\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(openintro)\nlibrary(knitr)\nlibrary(kableExtra)  # for table embellishments\nlibrary(Stat2Data)   # for empirical logit\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_bw(base_size = 20))\n```\n:::\n\n\n# Data\n\n## Risk of coronary heart disease {.midi}\n\nThis data set is from an ongoing cardiovascular study on residents of the town of Framingham, Massachusetts. We want to examine the relationship between various health characteristics and the risk of having heart disease.\n\n-   `high_risk`:\n\n    -   1: High risk of having heart disease in next 10 years\n    -   0: Not high risk of having heart disease in next 10 years\n\n-   `age`: Age at exam time (in years)\n\n-   `education`: 1 = Some High School, 2 = High School or GED, 3 = Some College or Vocational School, 4 = College\n\n-   `currentSmoker`: 0 = nonsmoker, 1 = smoker\n\n## Data prep\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease <- read_csv(here::here(\"slides\", \"data/framingham.csv\")) |>\n  select(age, education, TenYearCHD, totChol, currentSmoker) |>\n  drop_na() |> #consider the limitations of doing this\n  mutate(\n    high_risk = as.factor(TenYearCHD),\n    education = as.factor(education),\n    currentSmoker = as.factor(currentSmoker)\n  )\n\nheart_disease\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4,086 × 6\n     age education TenYearCHD totChol currentSmoker high_risk\n   <dbl> <fct>          <dbl>   <dbl> <fct>         <fct>    \n 1    39 4                  0     195 0             0        \n 2    46 2                  0     250 0             0        \n 3    48 1                  0     245 1             0        \n 4    61 3                  1     225 1             1        \n 5    46 3                  0     285 1             0        \n 6    43 2                  0     228 0             0        \n 7    63 1                  1     205 0             1        \n 8    45 2                  0     313 1             0        \n 9    52 1                  0     260 0             0        \n10    43 1                  0     225 1             0        \n# ℹ 4,076 more rows\n```\n:::\n:::\n\n\n## Modeling risk of coronary heart disease\n\nUsing `age` and `education`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrisk_fit <- logistic_reg() |>\n  set_engine(\"glm\") |>\n  fit(high_risk ~ age + education, \n      data = heart_disease, family = \"binomial\")\n```\n:::\n\n\n## Model output {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(risk_fit, conf.int = TRUE) |> \n  kable(format = \"markdown\", digits = 3)\n```\n\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) |   -5.508|     0.311|   -17.692|   0.000|   -6.125|    -4.904|\n|age         |    0.076|     0.006|    13.648|   0.000|    0.065|     0.087|\n|education2  |   -0.245|     0.113|    -2.172|   0.030|   -0.469|    -0.026|\n|education3  |   -0.236|     0.135|    -1.753|   0.080|   -0.504|     0.024|\n|education4  |   -0.024|     0.150|    -0.161|   0.872|   -0.323|     0.264|\n:::\n:::\n\n\n$$\n\\small{\\log\\Big(\\frac{\\hat{\\pi}}{1-\\hat{\\pi}}\\Big) = -5.508 + 0.076 ~ \\text{age} - 0.245 ~ \\text{ed2} - 0.236 ~ \\text{ed3} - 0.024 ~ \\text{ed4}}\n$$\n\n::: question\nShould we add `currentSmoker` to this model?\n:::\n\n# Comparing logistic regression models\n\n## Log likelihood\n\n$$\n\\log L = \\sum\\limits_{i=1}^n[y_i \\log(\\hat{\\pi}_i) + (1 - y_i)\\log(1 - \\hat{\\pi}_i)]\n$$\n\n-   Measure of how well the model fits the data\n\n-   Higher values of $\\log L$ are better\n\n-   **Deviance** = $-2 \\log L$\n\n    -   $-2 \\log L$ follows a $\\chi^2$ distribution with $n - p - 1$ degrees of freedom\n\n## Comparing nested models\n\n-   Suppose there are two models:\n\n    -   Reduced Model includes predictors $x_1, \\ldots, x_q$\n    -   Full Model includes predictors $x_1, \\ldots, x_q, x_{q+1}, \\ldots, x_p$\n\n-   We want to test the hypotheses\n\n    $$\n    \\begin{aligned}\n    H_0&: \\beta_{q+1} = \\dots = \\beta_p = 0 \\\\\n    H_A&: \\text{ at least one }\\beta_j \\text{ is not } 0\n    \\end{aligned}\n    $$\n\n-   To do so, we will use the **Drop-in-deviance test**, also known as the Nested Likelihood Ratio test\n\n## Drop-in-deviance test\n\n**Hypotheses:**\n\n$$\n\\begin{aligned}\nH_0&: \\beta_{q+1} = \\dots = \\beta_p = 0 \\\\\nH_A&: \\text{ at least 1 }\\beta_j \\text{ is not } 0\n\\end{aligned}\n$$\n\n. . .\n\n**Test Statistic:** $$G = (-2 \\log L_{reduced}) - (-2 \\log L_{full})$$\n\n. . .\n\n**P-value:** $P(\\chi^2 > G)$, calculated using a $\\chi^2$ distribution with degrees of freedom equal to the difference in the number of parameters in the full and reduced models\n\n## $\\chi^2$ distribution\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](19-logistic-compare_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Should we add `currentSmoker` to the model?\n\nFirst model, reduced:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrisk_fit_reduced <- logistic_reg() |>\n  set_engine(\"glm\") |>\n  fit(high_risk ~ age + education, \n      data = heart_disease, family = \"binomial\")\n```\n:::\n\n\n<br>\n\n. . .\n\nSecond model, full:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"3\"}\nrisk_fit_full <- logistic_reg() |>\n  set_engine(\"glm\") |>\n  fit(high_risk ~ age + education + currentSmoker, \n      data = heart_disease, family = \"binomial\")\n```\n:::\n\n\n## Should we add `currentSmoker` to the model?\n\nCalculate deviance for each model:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(dev_reduced <- glance(risk_fit_reduced)$deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3244.187\n```\n:::\n\n```{.r .cell-code}\n(dev_full <- glance(risk_fit_full)$deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3221.901\n```\n:::\n:::\n\n\n. . .\n\nDrop-in-deviance test statistic:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(test_stat <- dev_reduced - dev_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 22.2863\n```\n:::\n:::\n\n\n## Should we add `currentSmoker` to the model?\n\nCalculate the p-value using a `pchisq()`, with degrees of freedom equal to the number of new model terms in the second model:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npchisq(test_stat, 1, lower.tail = FALSE) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.348761e-06\n```\n:::\n:::\n\n\n. . .\n\n**Conclusion:** The p-value is very small, so we reject $H_0$. The data provide sufficient evidence that the coefficient of `currentSmoker` is not equal to 0. Therefore, we should add it to the model.\n\n## Drop-in-Deviance test in R {.midi}\n\n-   We can use the **`anova`** function to conduct this test\n\n-   Add **`test = \"Chisq\"`** to conduct the drop-in-deviance test\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(risk_fit_reduced$fit, risk_fit_full$fit, test = \"Chisq\") |>\n  tidy() |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> df.residual </th>\n   <th style=\"text-align:right;\"> residual.deviance </th>\n   <th style=\"text-align:right;\"> df </th>\n   <th style=\"text-align:right;\"> deviance </th>\n   <th style=\"text-align:right;\"> p.value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> high_risk ~ age + education </td>\n   <td style=\"text-align:right;\"> 4081 </td>\n   <td style=\"text-align:right;\"> 3244.187 </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> high_risk ~ age + education + currentSmoker </td>\n   <td style=\"text-align:right;\"> 4080 </td>\n   <td style=\"text-align:right;\"> 3221.901 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 22.286 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Model selection\n\nUse AIC or BIC for model selection\n\n$$\n\\begin{align}\n&AIC = - 2 * \\log L - {\\color{purple}n\\log(n)}+ 2(p +1)\\\\[5pt]\n&BIC =- 2 * \\log L - {\\color{purple}n\\log(n)} + log(n)\\times(p+1)\n\\end{align}\n$$\n\n## AIC from the `glance()` function\n\nLet's look at the AIC for the model that includes `age`, `education`, and `currentSmoker`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglance(risk_fit_full)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3233.901\n```\n:::\n:::\n\n\n. . .\n\n**Calculating AIC**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n- 2 * glance(risk_fit_full)$logLik + 2 * (5 + 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3233.901\n```\n:::\n:::\n\n\n## Comparing the models using AIC\n\nLet's compare the full and reduced models using AIC.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglance(risk_fit_reduced)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3254.187\n```\n:::\n\n```{.r .cell-code}\nglance(risk_fit_full)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3233.901\n```\n:::\n:::\n\n\n<br>\n\n::: question\nBased on AIC, which model would you choose?\n:::\n\n## Comparing the models using BIC\n\nLet's compare the full and reduced models using BIC\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglance(risk_fit_reduced)$BIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3285.764\n```\n:::\n\n```{.r .cell-code}\nglance(risk_fit_full)$BIC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3271.793\n```\n:::\n:::\n\n\n<br>\n\n::: question\nBased on BIC, which model would you choose?\n:::\n\n## Application exercise\n\n::: appex\n📋 [AE 14: Comparing logistic regression models](../ae/ae-14-logistic-compare.html)\n:::\n\n-   Sit with your lab groups.\n",
    "supporting": [
      "19-logistic-compare_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}