{
  "hash": "3aa7807b8e65ac8cba465682993da993",
  "result": {
    "markdown": "---\ntitle: \"Odds ratios\"\nsubtitle: \"Interpreting coefficients of the logistic regression model\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"2023-11-01\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 STA 210 - Fall 2023 -  Schedule](https://sta210-fa23.netlify.app/schedule)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false \n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n\n\n## Announcements\n\n-   HW 03 TODAY at 11:59pm\n\n-   Lab 06 due\n\n    -   Friday, November 03 at 11:59pm (Tuesday labs)\n\n    -   Sunday, November 05 at 11:59pm (Thursday labs)\n\n## Application exercise\n\n::: appex\n📋 AE 13: Logistic regression (continuation of AE 12)\n:::\n\n## Topics\n\n::: nonincremental\n-   Use the odds ratio to compare the odds of two groups\n\n-   Interpret the coefficients of a logistic regression model with\n\n    -   a single categorical predictor\n    -   a single quantitative predictor\n    -   multiple predictors\n:::\n\n## Computational setup\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(knitr)\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_bw(base_size = 20))\n```\n:::\n\n\n\n# Odds ratios\n\n## Risk of coronary heart disease {.midi}\n\nThis data set is from an ongoing cardiovascular study on residents of the town of Framingham, Massachusetts. We want to examine the relationship between various health characteristics and the risk of having heart disease.\n\n-   `high_risk`:\n\n    -   1: High risk of having heart disease in next 10 years\n    -   0: Not high risk of having heart disease in next 10 years\n\n-   `age`: Age at exam time (in years)\n\n-   `education`: 1 = Some High School, 2 = High School or GED, 3 = Some College or Vocational School, 4 = College\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\nRows: 4240 Columns: 16\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (16): male, age, education, currentSmoker, cigsPerDay, BPMeds, prevalent...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n:::\n\n\n\n## High risk vs. education\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|Education                         | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n:::\n:::\n\n\n\n## Compare the odds for two groups {.midi}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|Education                         | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n:::\n:::\n\n\n\n. . .\n\n-   We want to compare the risk of heart disease for those with a High School diploma/GED and those with a college degree.\n\n-   We'll use the **odds** to compare the two groups\n\n$$\n\\text{odds} = \\frac{P(\\text{success})}{P(\\text{failure})} = \\frac{\\text{# of successes}}{\\text{# of failures}}\n$$\n\n## Compare the odds for two groups {.midi}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|Education                         | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n:::\n:::\n\n\n\n-   Odds of being high risk for the **High school or GED** group: $\\frac{147}{1106} = 0.133$\n\n-   Odds of being high risk for the **College** group: $\\frac{70}{403} = 0.174$\n\n-   Based on this, we see those with a college degree had higher odds of being high risk for heart disease than those with a high school diploma or GED.\n\n## Odds ratio (OR) {.midi}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|Education                         | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n:::\n:::\n\n\n\nLet's summarize the relationship between the two groups. To do so, we'll use the **odds ratio (OR)**.\n\n$$\nOR = \\frac{\\text{odds}_1}{\\text{odds}_2} = \\frac{\\omega_1}{\\omega_2}\n$$\n\n## OR: College vs. High school or GED {.midi}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|Education                         | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n:::\n:::\n\n\n\n$$OR = \\frac{\\text{odds}_{College}}{\\text{odds}_{HS}} = \\frac{0.174}{0.133} = \\mathbf{1.308}$$\n\n. . .\n\nThe odds of being high risk for heart disease are 1.30 times higher for those with a college degree than those with a high school diploma or GED.\n\n## OR: College vs. Some high school {.midi}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|Education                         | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n:::\n:::\n\n\n\n$$OR = \\frac{\\text{odds}_{College}}{\\text{odds}_{Some HS}} = \\frac{70/403}{323/1397} = 0.751$$\n\n. . .\n\nThe odds of being high risk for having heart disease for those with a college degree are 0.751 times the odds of being high risk for heart disease for those with some high school.\n\n## More natural interpretation\n\n-   It's more natural to interpret the odds ratio with a statement with the odds ratio greater than 1.\n\n-   The odds of being high risk for heart disease are 1.33 times higher for those with some high school than those with a college degree.\n\n## Making the table 1\n\nFirst, rename the levels of the categorical variables:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease <- heart_disease |>\n  mutate(\n    high_risk_names = if_else(high_risk == \"1\", \"High risk\", \"Not high risk\"),\n    education_names = case_when(\n      education == \"1\" ~ \"Some high school\",\n      education == \"2\" ~ \"High school or GED\",\n      education == \"3\" ~ \"Some college or vocational school\",\n      education == \"4\" ~ \"College\"\n    ),\n    education_names = fct_relevel(education_names, \"Some high school\", \"High school or GED\", \"Some college or vocational school\", \"College\")\n  )\n```\n:::\n\n\n\n## Making the table 2\n\nThen, make the table:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease |>\n  count(education_names, high_risk_names) |>\n  pivot_wider(names_from = high_risk_names, values_from = n) |>\n  kable(col.names = c(\"Education\", \"High risk\", \"Not high risk\"))\n```\n:::\n\n\n\n## Deeper look into the code\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease |>\n  count(education_names, high_risk_names)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 8 × 3\n  education_names                   high_risk_names     n\n  <fct>                             <chr>           <int>\n1 Some high school                  High risk         323\n2 Some high school                  Not high risk    1397\n3 High school or GED                High risk         147\n4 High school or GED                Not high risk    1106\n5 Some college or vocational school High risk          88\n6 Some college or vocational school Not high risk     601\n7 College                           High risk          70\n8 College                           Not high risk     403\n```\n:::\n:::\n\n\n\n## Deeper look into the code\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"3\"}\nheart_disease |>\n  count(education_names, high_risk_names) |>\n  pivot_wider(names_from = high_risk_names, values_from = n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 3\n  education_names                   `High risk` `Not high risk`\n  <fct>                                   <int>           <int>\n1 Some high school                          323            1397\n2 High school or GED                        147            1106\n3 Some college or vocational school          88             601\n4 College                                    70             403\n```\n:::\n:::\n\n\n\n## Deeper look into the code\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"4\"}\nheart_disease |>\n  count(education_names, high_risk_names) |>\n  pivot_wider(names_from = high_risk_names, values_from = n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n|education_names                   | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n:::\n:::\n\n\n\n## Deeper look into the code\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"4\"}\nheart_disease |>\n  count(education_names, high_risk_names) |>\n  pivot_wider(names_from = high_risk_names, values_from = n) |>\n  kable(col.names = c(\"Education\", \"High risk\", \"Not high risk\"))\n```\n\n::: {.cell-output-display}\n|Education                         | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n:::\n:::\n\n\n\n# Logistic regression: categorical predictor\n\n## Categorical predictor {.midi}\n\nRecall: Education - 1 = Some High School, 2 = High School or GED, 3 = Some College or Vocational School, 4 = College\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_edu_fit <- logistic_reg() |>\n  set_engine(\"glm\") |>\n  fit(high_risk ~ education, data  = heart_disease, family = \"binomial\")\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(heart_edu_fit) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -1.464|     0.062|   -23.719|   0.000|\n|education2  |   -0.554|     0.107|    -5.159|   0.000|\n|education3  |   -0.457|     0.130|    -3.520|   0.000|\n|education4  |   -0.286|     0.143|    -1.994|   0.046|\n:::\n:::\n\n\n\n## Interpreting `education4`: log-odds\n\n::: small\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -1.464|     0.062|   -23.719|   0.000|\n|education2  |   -0.554|     0.107|    -5.159|   0.000|\n|education3  |   -0.457|     0.130|    -3.520|   0.000|\n|education4  |   -0.286|     0.143|    -1.994|   0.046|\n:::\n:::\n\n\n:::\n\nThe **log-odds** of being high risk for heart disease are expected to be 0.286 less for those with a college degree compared to those with some high school (the baseline group).\n\n. . .\n\n::: callout-warning\nWe would not use the interpretation in terms of log-odds in practice.\n:::\n\n## Interpreting `education4`: odds\n\n::: small\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -1.464|     0.062|   -23.719|   0.000|\n|education2  |   -0.554|     0.107|    -5.159|   0.000|\n|education3  |   -0.457|     0.130|    -3.520|   0.000|\n|education4  |   -0.286|     0.143|    -1.994|   0.046|\n:::\n:::\n\n\n:::\n\nThe **odds** of being high risk for heart disease for those with a college degree are expected to be 0.751 (exp{-0.286}) **times** the odds for those with some high school.\n\n## Coefficients + odds ratios\n\nThe model coefficient, -0.286, is the expected change in the log-odds when going from the *Some high school* group to the *College* group.\n\n. . .\n\nTherefore, $e^{-0.286}$ = 0.751 is the expected change in the **odds** when going from the *Some high school* group to the *College* group.\n\n. . .\n\n$$\nOR  = e^{\\hat{\\beta}_j} = \\exp\\{\\hat{\\beta}_j\\}\n$$\n\n# Logistic regression: quantitative predictor\n\n## Quantitative predictor\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_age_fit <- logistic_reg() |>\n  set_engine(\"glm\") |>\n  fit(high_risk ~ age, data  = heart_disease, family = \"binomial\")\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(heart_age_fit) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.619|     0.288|   -19.498|       0|\n|age         |    0.076|     0.005|    14.174|       0|\n:::\n:::\n\n\n\n## Interpreting `age`: log-odds\n\n::: small\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.619|     0.288|   -19.498|       0|\n|age         |    0.076|     0.005|    14.174|       0|\n:::\n:::\n\n\n:::\n\nFor each additional year in age, the log-odds of being high risk for heart disease are expected to increase by 0.076.\n\n. . .\n\n::: callout-warning\nWe would not use the interpretation in terms of log-odds in practice.\n:::\n\n## Interpreting `age`: odds\n\n::: small\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.619|     0.288|   -19.498|       0|\n|age         |    0.076|     0.005|    14.174|       0|\n:::\n:::\n\n\n:::\n\n-   For each additional year in age, the odds of being high risk for heart disease are expected to multiply by a factor of 1.08 (exp{0.076}).\n-   **Alternate interpretation:** For each additional year in age, the odds of being high risk for heart disease are expected to increase by 8%.\n\n# Logistic regression: multiple predictors\n\n## Multiple predictors\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_edu_age_fit <- logistic_reg() |>\n  set_engine(\"glm\") |>\n  fit(high_risk ~ education + age, data  = heart_disease, family = \"binomial\")\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(heart_edu_age_fit) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n|age         |    0.073|     0.005|    13.385|   0.000|\n:::\n:::\n\n\n\n## Interpretation in terms of log-odds\n\n::: small\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n|age         |    0.073|     0.005|    13.385|   0.000|\n:::\n:::\n\n\n:::\n\n`education4`: The **log-odds** of being high risk for heart disease are expected to be 0.020 less for those with a college degree compared to those with some high school, **holding age constant.**\n\n. . .\n\n::: callout-warning\nWe would not use the interpretation in terms of log-odds in practice.\n:::\n\n## Interpretation in terms of log-odds\n\n::: small\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n|age         |    0.073|     0.005|    13.385|   0.000|\n:::\n:::\n\n\n:::\n\n`age`: For each additional year in age, the log-odds of being high risk for heart disease are expected to increase by 0.073, **holding education level constant.**\n\n. . .\n\n::: callout-warning\nWe would not use the interpretation in terms of log-odds in practice.\n:::\n\n## Interpretation in terms of odds {.midi}\n\n::: small\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n|age         |    0.073|     0.005|    13.385|   0.000|\n:::\n:::\n\n\n:::\n\n`education4`: The **odds** of being high risk for heart disease for those with a college degree are expected to be 0.98 (exp{-0.020}) **times** the odds for those with some high school, **holding age constant**.\n\n::: callout-note\nIn logistic regression with 2+ predictors, $exp\\{\\hat{\\beta}_j\\}$ is often called the **adjusted odds ratio (AOR).**\n:::\n\n## Interpretation in terms of odds {.midi}\n\n::: small\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n|age         |    0.073|     0.005|    13.385|   0.000|\n:::\n:::\n\n\n:::\n\n`age`: For each additional year in age, the odds being high risk for heart disease are expected to multiply by a factor of 1.08 (`exp(0.073)`), **holding education level constant**.\n\n::: callout-note\nIn logistic regression with 2+ predictors, $exp\\{\\hat{\\beta}_j\\}$ is often called the **adjusted odds ratio (AOR).**\n:::\n\n## Recap\n\n-   Use the odds ratio to compare the odds of two groups\n\n-   Interpret the coefficients of a logistic regression model with\n\n    -   a single categorical predictor\n    -   a single quantitative predictor\n    -   multiple predictors\n",
    "supporting": [
      "17-odds-ratios_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}