{
  "hash": "a20ef094925781518612b10da21051e7",
  "result": {
    "markdown": "---\ntitle: \"Review of multiple linear regression\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"2024-01-17\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 STA 310 - Spring 2024](https://sta310-sp24.netlify.app)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false \n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  warning: false\n  message: false\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n:::\n:::\n\n\nclass: middle, center\n\n\\##[Click for PDF of slides](02-mlr-review-pt1.pdf)\n\n------------------------------------------------------------------------\n\n## Announcements\n\n-   Labs start Thursday\n    -   [Install R and configure GitHub](https://github.com/sta310-sp22/computing/blob/main/README.md)\n-   Office hours this week:\n    -   Thu 2 - 3pm & Fri 1 - 2pm online (links in Sakai)\n    -   Full office hours schedule starts Tue, Jan 19\n-   Fill out [All About You Survey](https://duke.qualtrics.com/jfe/form/SV_1X1ryORVK6JJwkm)\n\n------------------------------------------------------------------------\n\nclass: middle\n\n## Questions from last time?\n\n------------------------------------------------------------------------\n\nclass: middle, inverse\n\n## Linear least squares regression (LLSR) vs.\n\n## Generalized linear models (GLM) vs.\n\n## Multilevel models\n\n------------------------------------------------------------------------\n\n## Assumptions for linear regression\n\n--\n\n**L**inearity: Linear relationship between mean response and predictor variable(s)\n\n--\n\n**I**ndependence: Residuals are independent. There is no connection between how far any two points lie above or below regression line.\n\n--\n\n**N**ormality: Response follows a normal distribution at each level of the predictor (or combination of predictors)\n\n--\n\n**E**qual variance: Variability (variance or standard deviation) of the response is equal for all levels of the predictor (or combination of predictors)\n\n**Use residual plots to check that the conditions hold before using the model for statistical inference.**\n\n------------------------------------------------------------------------\n\n## Assumptions for linear regression\n\n.pull-left\\[\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-mlr-review-pt1_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n.small\\[Modified from Figure 1.1. in BMLR\\] \\]\n\n.pull-right\\[ .midi\\[**L**inearity: Linear relationship between mean of the response $Y$ and the predictor $X$\\]\n\n.midi\\[**I**ndependence: No connection between how any two points lie above or below the regression line\\]\n\n.midi\\[**N**ormality: Response, $Y$, follows a normal distribution at each level of the predictor, $X$ (indicated by red curves)\\]\n\n.midi\\[**E**qual variance: Variance (or standard deviation) of the response, $Y$, is equal for all levels of the predictor, $X$\\] \\] \\]\n\n------------------------------------------------------------------------\n\n## Are the assumptions violated?\n\n[Click here](https://forms.gle/N3PftSk2tEJRTxCE6) for poll.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div class=\"countdown\" id=\"timer_68d66716\" data-update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;margin:5%;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">04</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Beyond linear regression\n\n-   When we use linear least squares regression to draw conclusions, we do so under the assumption that L.I.N.E. are all met.\n\n-   **Generalized linear models** require different assumptions and can accommodate violations in L.I.N.E.\n\n    -   Relationship between response and predictor(s) can be nonlinear\n    -   Response variable can be non-normal\n    -   Variance in response can differ at each level of predictor(s)\n\n**But the independence assumption must hold!**\n\n-   **Multilevel models** will be used for data with correlated observations\n\n------------------------------------------------------------------------\n\nclass: middle, inverse\n\n## Review of multiple linear regression\n\n------------------------------------------------------------------------\n\n## Data: Kentucky Derby Winners\n\n.midi\\[ Today's data is from the Kentucky Derby, an annual 1.25-mile horse race held at the Churchill Downs race track in Louisville, KY. The data is in the file [derbyplus.csv](data/derbyplus.csv) and contains information for races 1896 - 2017. \\]\n\n.pull-left\\[\n\n.midi\\[**Response variable**\\]\n\n-   .midi\\[`speed`: Average speed of the winner in feet per second (ft/s)\\]\n\n.midi\\[**Additional variable**\\] .midi\\[- `winner`: Winning horse\\] \\]\n\n.pull-right\\[ .midi\\[**Predictor variables**\\] - .midi\\[`year`: Year of the race\\] - .midi\\[`condition`: Condition of the track (good, fast, slow)\\] - .midi\\[`starters`: Number of horses who raced\\]\\]\n\n------------------------------------------------------------------------\n\n## Data\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nderby <- read_csv(\"data/derbyplus.csv\")\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nderby %>%\n  head(5) %>% kable()\n```\n\n::: {.cell-output-display}\n| year|winner        |condition | speed| starters|\n|----:|:-------------|:---------|-----:|--------:|\n| 1896|Ben Brush     |good      | 51.66|        8|\n| 1897|Typhoon II    |slow      | 49.81|        6|\n| 1898|Plaudit       |good      | 51.16|        4|\n| 1899|Manuel        |fast      | 50.00|        5|\n| 1900|Lieut. Gibson |fast      | 52.28|        7|\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n![](img/data-analysis-life-cycle.png)\n\n------------------------------------------------------------------------\n\n## Exploratory data analysis (EDA)\n\n-   Once you're ready for the statistical analysis (explore), the first step should always be **exploratory data analysis**.\n\n-   The EDA will help you\n\n    -   begin to understand the variables and observations\n    -   identify outliers or potential data entry errors\n    -   begin to see relationships between variables\n    -   identify the appropriate model and identify a strategy\n\n-   The EDA is exploratory; formal modeling and statistical inference should be used to draw conclusions.\n\n------------------------------------------------------------------------\n\n## Plots for univariate EDA\n\n.panelset.sideways\\[ .panel\\[.panel-name\\[Plot\\]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-mlr-review-pt1_files/figure-revealjs/univar-eda-plot-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\\] .panel\\[.panel-name\\[Code\\]\n\n.small\\[\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np1 <- ggplot(data = derby, aes(x = speed)) + \n  geom_histogram(fill = colors$green, color = \"black\") + \n  labs(x = \"Winning speed (ft/s)\", y = \"Count\")\n\np2 <- ggplot(data = derby, aes(x = starters)) + \n  geom_histogram(fill = colors$green, color = \"black\") + \n  labs(x = \"Starters\", y = \"Count\")\n\np3 <- ggplot(data = derby, aes(x = condition)) +\n   geom_bar(fill = colors$green, color = \"black\", aes(x = ))\n\np1 + (p2 / p3) + \n  plot_annotation(title = \"Univariate data analysis\")\n```\n:::\n\n\n\\] \\] \\]\n\n------------------------------------------------------------------------\n\n## Plots for bivariate EDA\n\n.panelset.sideways\\[ .panel\\[.panel-name\\[Plot\\]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-mlr-review-pt1_files/figure-revealjs/bivar-eda-plot-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\\] .panel\\[.panel-name\\[Code\\]\n\n.small\\[\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np4 <- ggplot(data = derby, aes(x = starters, y = speed)) + \n  geom_point() + \n  labs(x = \"Starters\", y = \"Speed (ft / s)\")\n\np5 <- ggplot(data = derby, aes(x = year, y = speed)) + \n  geom_point() + \n  labs(x = \"Year\", y = \"Speed (ft / s)\")\n\np6 <- ggplot(data = derby, aes(x = condition, y = speed)) + \n  geom_boxplot(fill = colors$green, color = \"black\") + \n  labs(x = \"Conditions\", y = \"Speed (ft / s)\")\n\n(p4 + p5) + p6 +\n  plot_annotation(title = \"Bivariate data analysis\")\n```\n:::\n\n\n\\] \\] \\]\n\n------------------------------------------------------------------------\n\n## Scatterplot matrix\n\n.midi\\[ A **scatterplot matrix** helps quickly visualize relationships between many variable pairs. They are particularly useful to identify potentially correlated predictors.\\]\n\n.panelset.sideways\\[\n\n.panel\\[.panel-name\\[Plot\\]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-mlr-review-pt1_files/figure-revealjs/scatterplot-matrix-plot-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\\]\n\n.panel\\[.panel-name\\[Code\\] .small\\[\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#library(GGally)\nggpairs(data = derby, \n        columns = c(\"condition\", \"year\", \"starters\", \"speed\"))\n```\n:::\n\n\n\\] \\] \\]\n\n------------------------------------------------------------------------\n\n## Plots for multivariate EDA\n\nPlot the relationship between the response and a predictor based on levels of another predictor to assess potential interactions.\n\n.panelset.sideways\\[\n\n.panel\\[.panel-name\\[Plot\\]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-mlr-review-pt1_files/figure-revealjs/multivar-eda-plot-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\\]\n\n.panel\\[.panel-name\\[Code\\] .small\\[\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#library(viridis)\nggplot(data = derby, aes(x = year, y = speed, color = condition, \n                         shape = condition, linetype = condition)) + \n  geom_point() + \n  geom_smooth(method = \"lm\", se = FALSE, aes(linetype = condition)) + \n  labs(x = \"Year\", y = \"Speed (ft/s)\", color = \"Condition\",\n       title = \"Speed vs. year\", \n       subtitle = \"by track condition\") +\n  guides(lty = FALSE, shape = FALSE) +\n  scale_color_viridis_d(end = 0.9)\n```\n:::\n\n\n\\] \\] \\]\n\n------------------------------------------------------------------------\n\n## Model 1: Main effects model\n\n.panelset.sideways\\[ .panel\\[.panel-name\\[Output\\]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term          | estimate| std.error| statistic| p.value|\n|:-------------|--------:|---------:|---------:|-------:|\n|(Intercept)   |    8.197|     4.508|     1.818|   0.072|\n|starters      |   -0.005|     0.017|    -0.299|   0.766|\n|year          |    0.023|     0.002|     9.766|   0.000|\n|conditiongood |   -0.443|     0.231|    -1.921|   0.057|\n|conditionslow |   -1.543|     0.161|    -9.616|   0.000|\n:::\n:::\n\n\n\\]\n\n.panel\\[.panel-name\\[Code\\] .small\\[\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fit and display model\nmodel1 <- lm(speed ~ starters + year + condition, data = derby)\ntidy(model1) %>% \n  kable(digits = 3)\n```\n:::\n\n\n\\] \\] \\]\n\n------------------------------------------------------------------------\n\n## Interpretation\n\n$$\\widehat{speed} = 8.197 - 0.005 ~ starters + 0.023 ~ year - 0.443 ~ good - 1.543 ~ slow$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term          | estimate| std.error| statistic| p.value|\n|:-------------|--------:|---------:|---------:|-------:|\n|(Intercept)   |    8.197|     4.508|     1.818|   0.072|\n|starters      |   -0.005|     0.017|    -0.299|   0.766|\n|year          |    0.023|     0.002|     9.766|   0.000|\n|conditiongood |   -0.443|     0.231|    -1.921|   0.057|\n|conditionslow |   -1.543|     0.161|    -9.616|   0.000|\n:::\n:::\n\n\n--\n\n.question\\[ 1. Write out the interpretations for `starters` and `conditiongood`. 2. Does the intercept have a meaningful interpretation? \\]\n\n------------------------------------------------------------------------\n\n## Centering\n\n**Centering**: Subtract a constant from each observation of a given variable\n\n-   Do this to make interpretation of model parameters more meaningful (particularly intercept)\n\n-   In STA 210, we used **mean-centering** where we subtracted the mean from each observation of given variable\n\n-   How does centering change the model?\n\n------------------------------------------------------------------------\n\n## Centering `year`\n\n.midi\\[\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nderby <- derby %>%\n  mutate(yearnew = year - 1896) #1896 = starting year\n```\n:::\n\n\n\\]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term          | estimate| std.error| statistic| p.value|\n|:-------------|--------:|---------:|---------:|-------:|\n|(Intercept)   |   52.175|     0.194|   269.079|   0.000|\n|starters      |   -0.005|     0.017|    -0.299|   0.766|\n|yearnew       |    0.023|     0.002|     9.766|   0.000|\n|conditiongood |   -0.443|     0.231|    -1.921|   0.057|\n|conditionslow |   -1.543|     0.161|    -9.616|   0.000|\n:::\n:::\n\n\n$$\\widehat{speed} = 52.175 - 0.005 ~ starters + 0.023 ~ yearnew - 0.443 ~ good - 1.543 ~ slow$$\n\n------------------------------------------------------------------------\n\n## Model 1: Check model assumptions\n\n.panelset.sideways\\[ .panel\\[.panel-name\\[Plots\\]\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#library(ggfortify)\nautoplot(model1Cent)\n```\n\n::: {.cell-output-display}\n![](02-mlr-review-pt1_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\\]\n\n.panel\\[.panel-name\\[Poll\\] [Click here](https://forms.gle/iHfWR1igqpsM7Gr48) for poll.\\] \\]\n\n------------------------------------------------------------------------\n\nclass: middle, inverse\n\n## Model 2\n\n------------------------------------------------------------------------\n\n## Add quadratic effect for year?\n\n.panelset.sideways\\[ .panel\\[.panel-name\\[Plot\\]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-mlr-review-pt1_files/figure-revealjs/year-quad-plot-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\\]\n\n.panel\\[.panel-name\\[Code\\] .small\\[\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = derby, aes(x = yearnew, y = speed)) + \n  geom_point(alpha = 0.7) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"blue\") + \n  geom_smooth(se = FALSE, color = \"red\", linetype = 2) + \n  labs(x = \"Years since 1896\", y = \"Speed (ft/s)\", \n       title = \"Speed vs. Years since 1896\")\n```\n:::\n\n\n\\] \\] \\]\n\n------------------------------------------------------------------------\n\n## Model 2: Add $yearnew^2$\n\n.panelset.sideways\\[ .panel\\[.panel-name\\[Output\\]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term          | estimate| std.error| statistic| p.value|\n|:-------------|--------:|---------:|---------:|-------:|\n|(Intercept)   |  51.4130|    0.1826|  281.5645|  0.0000|\n|starters      |  -0.0253|    0.0136|   -1.8588|  0.0656|\n|yearnew       |   0.0700|    0.0061|   11.4239|  0.0000|\n|I(yearnew^2)  |  -0.0004|    0.0000|   -8.0411|  0.0000|\n|conditiongood |  -0.4770|    0.1857|   -2.5689|  0.0115|\n|conditionslow |  -1.3927|    0.1305|  -10.6701|  0.0000|\n:::\n:::\n\n\n\\]\n\n.panel\\[.panel-name\\[Code\\] .small\\[\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel2 <- lm(speed ~ starters + yearnew + I(yearnew^2) + condition, \n             data = derby)\ntidy(model2) %>% kable(digits = 4)\n```\n:::\n\n\n\\] \\] \\]\n\n------------------------------------------------------------------------\n\n## Interpreting quadratic effects\n\n$$\\hat{y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 ~ x_1  + \\hat{\\beta}_2 ~ x_2 + \\hat{\\beta}_3 ~ x_2^2$$\n\n**General interpretation**: When $x_2$ increases from a to b, $y$ is expected to change by $\\hat{\\beta}_2(b - a) + \\hat{\\beta}_3(b^2 - a^2)$, holding $x_1$ constant.\n\n<br>\n\n--\n\n.question\\[\n\n$$\\begin{aligned}\\widehat{speed} = &51.413 - 0.025 ~ starters + 0.070 ~ yearnew \\\\\n& - 0.0004 ~ yearnew^2 - 0.477 ~ good - 1.393 ~ slow\\end{aligned}$$\n\nInterpret the effect of year for the 5 most recent years (2013 - 2017). \\]\n\n<!-- Ended here in lecture-->\n\n------------------------------------------------------------------------\n\n## Model 2: Check model assumptions\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-mlr-review-pt1_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\nclass: middle, inverse\n\n## \\## Model 3\n\n## Include interaction term?\n\nRecall from the EDA...\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-mlr-review-pt1_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Model 3: Add interaction term\n\n$$\\begin{aligned}\\widehat{speed} = & 52.387 - 0.003 ~ starters + 0.020 ~ yearnew - 1.070 ~ good - 2.183 ~ slow \\\\ &+0.012 ~ yearnew \\times good + 0.012 ~ yearnew \\times slow \\end{aligned}$$\n\n.panelset.sideways\\[ .panel\\[.panel-name\\[Output\\]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term                  | estimate| std.error| statistic| p.value|\n|:---------------------|--------:|---------:|---------:|-------:|\n|(Intercept)           |   52.387|     0.200|   262.350|   0.000|\n|starters              |   -0.003|     0.016|    -0.189|   0.850|\n|yearnew               |    0.020|     0.003|     7.576|   0.000|\n|conditiongood         |   -1.070|     0.423|    -2.527|   0.013|\n|conditionslow         |   -2.183|     0.270|    -8.097|   0.000|\n|yearnew:conditiongood |    0.012|     0.008|     1.598|   0.113|\n|yearnew:conditionslow |    0.012|     0.004|     2.866|   0.005|\n:::\n:::\n\n\n\\]\n\n.panel\\[.panel-name\\[Code\\]\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel3 <- lm(speed ~ starters + yearnew + condition +\n               yearnew * condition, \n             data = derby)\ntidy(model3) %>% kable(digits = 4)\n```\n:::\n\n\n\\] .panel\\[.panel-name\\[Assumptions\\]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-mlr-review-pt1_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\\] \\]\n\n------------------------------------------------------------------------\n\n## Interpreting interaction effects\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term                  | estimate| std.error| statistic| p.value|\n|:---------------------|--------:|---------:|---------:|-------:|\n|(Intercept)           |   52.387|     0.200|   262.350|   0.000|\n|starters              |   -0.003|     0.016|    -0.189|   0.850|\n|yearnew               |    0.020|     0.003|     7.576|   0.000|\n|conditiongood         |   -1.070|     0.423|    -2.527|   0.013|\n|conditionslow         |   -2.183|     0.270|    -8.097|   0.000|\n|yearnew:conditiongood |    0.012|     0.008|     1.598|   0.113|\n|yearnew:conditionslow |    0.012|     0.004|     2.866|   0.005|\n:::\n:::\n\n\n[Click here](https://forms.gle/BrufiFdhQAi4WBWeA) for poll\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div class=\"countdown\" id=\"timer_590c99ec\" data-update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;margin:5%;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">04</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Which model would you choose?\n\n.panelset.sideways\\[ .panel\\[.panel-name\\[Output\\]\n\n.midi\\[**Model 1: Main effects**\\]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n| r.squared| adj.r.squared|     AIC|     BIC|\n|---------:|-------------:|-------:|-------:|\n|      0.73|         0.721| 259.478| 276.302|\n:::\n:::\n\n\n.midi\\[**Model 2: Main effects +** $year^2$\\]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n| r.squared| adj.r.squared|     AIC|     BIC|\n|---------:|-------------:|-------:|-------:|\n|     0.827|         0.819| 207.429| 227.057|\n:::\n:::\n\n\n.midi\\[\\*\\*Model 3: Main effects + interaction\\]\\*\\*\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n| r.squared| adj.r.squared|     AIC|     BIC|\n|---------:|-------------:|-------:|-------:|\n|     0.751|         0.738| 253.584| 276.016|\n:::\n:::\n\n\n\\]\n\n.panel\\[.panel-name\\[Code\\]\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Model 1\nglance(model1Cent) %>%\n  select(r.squared, adj.r.squared, AIC, BIC) %>%\n  kable(digits = 3)\n\n# Model2\nglance(model2) %>%\n  select(r.squared, adj.r.squared, AIC, BIC) %>%\n  kable(digits = 3)\n\n# Model 3\nglance(model3) %>%\n  select(r.squared, adj.r.squared, AIC, BIC) %>%\n  kable(digits = 3)\n```\n:::\n\n\n\\] \\]\n\n------------------------------------------------------------------------\n\n## Characteristics of a \"good\" final model\n\n-   Model can be used to answer primary research questions\n-   Predictor variables control for important covariates\n-   Potential interactions have been investigated\n-   Variables are centered, as needed, for more meaningful interpretations\n-   unnecessary terms are removed\n-   Assumptions are met and influential points have been addressed\n-   model tells a \"persuasive story parsimoniously\"\n\n<br>\n\n.small\\[List from Section 1.6.7 of [BMLR](https://bookdown.org/roback/bookdown-BeyondMLR/)\\]\n\n------------------------------------------------------------------------\n\n## Acknowledgements\n\nThese slides are based on content in [BMLR: Chapter 1 - Review of Multiple Linear Regression](https://bookdown.org/roback/bookdown-BeyondMLR/ch-MLRreview.html)\n\n## Model 1: Main effects model (with centering)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term          | estimate| std.error| statistic| p.value|\n|:-------------|--------:|---------:|---------:|-------:|\n|(Intercept)   |   52.175|     0.194|   269.079|   0.000|\n|starters      |   -0.005|     0.017|    -0.299|   0.766|\n|yearnew       |    0.023|     0.002|     9.766|   0.000|\n|conditiongood |   -0.443|     0.231|    -1.921|   0.057|\n|conditionslow |   -1.543|     0.161|    -9.616|   0.000|\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Model 2: Include quadratic effect for year\n\n.midi\\[\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term          | estimate| std.error| statistic| p.value|\n|:-------------|--------:|---------:|---------:|-------:|\n|(Intercept)   |  51.4130|    0.1826|  281.5645|  0.0000|\n|starters      |  -0.0253|    0.0136|   -1.8588|  0.0656|\n|yearnew       |   0.0700|    0.0061|   11.4239|  0.0000|\n|I(yearnew^2)  |  -0.0004|    0.0000|   -8.0411|  0.0000|\n|conditiongood |  -0.4770|    0.1857|   -2.5689|  0.0115|\n|conditionslow |  -1.3927|    0.1305|  -10.6701|  0.0000|\n:::\n:::\n\n\n\\]\n\n------------------------------------------------------------------------\n\n## Model 2: Check model assumptions\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-mlr-review-pt1_files/figure-revealjs/unnamed-chunk-25-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\nclass: middle, inverse\n\n## \\## Model 3\n\n## Include interaction term?\n\nRecall from the EDA...\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-mlr-review-pt1_files/figure-revealjs/unnamed-chunk-26-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Model 3: Include interaction term\n\n$$\\begin{aligned}\\widehat{speed} = & 52.387 - 0.003 ~ starters + 0.020 ~ yearnew - 1.070 ~ good - 2.183 ~ slow \\\\ &+0.012 ~ yearnew \\times good + 0.012 ~ yearnew \\times slow \\end{aligned}$$\n\n.panelset.sideways\\[ .panel\\[.panel-name\\[Output\\]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term                  | estimate| std.error| statistic| p.value|\n|:---------------------|--------:|---------:|---------:|-------:|\n|(Intercept)           |   52.387|     0.200|   262.350|   0.000|\n|starters              |   -0.003|     0.016|    -0.189|   0.850|\n|yearnew               |    0.020|     0.003|     7.576|   0.000|\n|conditiongood         |   -1.070|     0.423|    -2.527|   0.013|\n|conditionslow         |   -2.183|     0.270|    -8.097|   0.000|\n|yearnew:conditiongood |    0.012|     0.008|     1.598|   0.113|\n|yearnew:conditionslow |    0.012|     0.004|     2.866|   0.005|\n:::\n:::\n\n\n\\]\n\n.panel\\[.panel-name\\[Code\\]\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel3 <- lm(speed ~ starters + yearnew + condition +\n               yearnew * condition, \n             data = derby)\ntidy(model3) %>% kable(digits = 4)\n```\n:::\n\n\n\\] .panel\\[.panel-name\\[Assumptions\\]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-mlr-review-pt1_files/figure-revealjs/unnamed-chunk-28-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\\] \\]\n\n------------------------------------------------------------------------\n\n## Interpreting interaction effects\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term                  | estimate| std.error| statistic| p.value|\n|:---------------------|--------:|---------:|---------:|-------:|\n|(Intercept)           |   52.387|     0.200|   262.350|   0.000|\n|starters              |   -0.003|     0.016|    -0.189|   0.850|\n|yearnew               |    0.020|     0.003|     7.576|   0.000|\n|conditiongood         |   -1.070|     0.423|    -2.527|   0.013|\n|conditionslow         |   -2.183|     0.270|    -8.097|   0.000|\n|yearnew:conditiongood |    0.012|     0.008|     1.598|   0.113|\n|yearnew:conditionslow |    0.012|     0.004|     2.866|   0.005|\n:::\n:::\n\n\n[Click here](https://forms.gle/BrufiFdhQAi4WBWeA) for poll\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div class=\"countdown\" id=\"timer_ec3a86ee\" data-update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;margin:5%;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">04</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Measures of model performance\n\n-   $\\color{#4187aa}{R^2}$: Proportion of variability in the response explained by the model.\n    -   Will always increase as predictors are added, so it shouldn't be used to compare models\n-   $\\color{#4187aa}{Adj. R^2}$: Similar to $R^2$ with a penalty for extra terms\n\n--\n\n-   $\\color{#4187aa}{AIC}$: Likelihood-based approach balancing model performance and complexity\n\n-   $\\color{#4187aa}{BIC}$: Similar to AIC with stronger penalty for extra terms\n\n--\n\n-   **Nested F Test (extra sum of squares F test)**: Generalization of t-test for individual coefficients to perform significance tests on nested models\n\n------------------------------------------------------------------------\n\n## Which model would you choose?\n\nUse the **`glance`** function to get model statistics.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|model  | r.squared| adj.r.squared|     AIC|     BIC|\n|:------|---------:|-------------:|-------:|-------:|\n|Model1 |     0.730|         0.721| 259.478| 276.302|\n|Model2 |     0.827|         0.819| 207.429| 227.057|\n|Model3 |     0.751|         0.738| 253.584| 276.016|\n:::\n:::\n\n\n## **Which model would you choose?**\n\n## Characteristics of a \"good\" final model\n\n-   Model can be used to answer primary research questions\n-   Predictor variables control for important covariates\n-   Potential interactions have been investigated\n-   Variables are centered, as needed, for more meaningful interpretations\n-   Unnecessary terms are removed\n-   Assumptions are met and influential points have been addressed\n-   Model tells a \"persuasive story parsimoniously\"\n\n<br>\n\n.footnote\\[List from Section 1.6.7 of [BMLR](https://bookdown.org/roback/bookdown-BeyondMLR/)\\]\n\n------------------------------------------------------------------------\n\nclass: middle, inverse\n\n## Inference for multiple linear regression\n\n------------------------------------------------------------------------\n\n## Inference for regression\n\nUse statistical inference to\n\n-   Determine if predictors are statistically significant (not necessarily practically significant!)\n-   Quantify uncertainty in coefficient estimates\n-   Quantify uncertainty in model predictions\n\n<br>\n\nIf L.I.N.E. assumptions are met, we can conduct inference using the $t$ distribution and estimated standard errors\n\n------------------------------------------------------------------------\n\n## Inference for regression\n\n.pull-left\\[\n\nWhen L.I.N.E. conditions are met\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-mlr-review-pt1_files/figure-revealjs/unnamed-chunk-32-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\\]\n\n.pull-right\\[\n\n-   Use least squares regression to get the estimates $\\hat{\\beta}_0$, $\\hat{\\beta}_1$, and $\\hat{\\sigma}^2$\n\n-   $\\hat{\\sigma}$ is the **regression standard error**\n\n$$\\hat{\\sigma} = \\sqrt{\\frac{\\sum_{i=1}^n(y_i - \\hat{y}_i)^2}{n - p - 1}} = \\sqrt{\\frac{\\sum_{i=1}^n e_i^2}{n-p-1}}$$\n\nwhere $p$ is the number of non-intercept terms in the model\n\n(p = 1 in simple linear regression) \\]\n\n------------------------------------------------------------------------\n\n## Inference for $\\beta_j$\n\n-   Suppose we have the following model:\n\n$$y_i = \\beta_0 + \\beta_1 x_{1i} + \\beta_2 x_{2i} + \\dots + \\beta_p x_{pi} + \\epsilon_i \\hspace{5mm} \\epsilon \\sim N(0, \\sigma^2)$$\n\n--\n\n-   We use least squares regression to get estimates for the parameters $\\beta_0, \\beta_1, \\ldots, \\beta_p$ and $\\sigma^2$. The regression equation is\n\n$$\\hat{y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 x_1 + \\hat{\\beta}_2 x_2 + \\dots + \\hat{\\beta}_p x_p$$\n\n-   When the L.I.N.E. assumptions are met, $\\hat{\\beta}_j \\sim N(\\beta_j, SE_{\\hat{\\beta}_j})$.\n    -   The objective of statistical inference is to understand $\\beta_j$\n    -   Use $\\hat{\\sigma}$ to estimate $SE_{\\hat{\\beta}_j}$, the **standard error of** $\\hat{\\beta}_j$\n\n------------------------------------------------------------------------\n\n## Inference for $\\beta_j$\n\n.eq\\[ $$SE_{\\hat{\\beta}_j} = \\hat{\\sigma}\\sqrt{\\frac{1}{(n-1)s_{x_j}^2}}$$\\]\n\nConduct inference for $\\beta_j$ using a $t$ distribution with $n-p-1$ degrees of freedom (df).\n\n-   $\\hat{\\beta}_j$ follows a $t$ distribution, because $\\hat{\\sigma}$ (not $\\sigma$) is used to calculate the standard error of $\\hat{\\beta}_j$.\n\n-   The distribution has $n-p-1$ df because we use up $p + 1$ df to calculate $\\hat{\\sigma}$, so there are $n - p - 1$ df left to understand variability.\n\n------------------------------------------------------------------------\n\n## Hypothesis test for $\\beta_j$\n\n.pull-left\\[ 1️⃣ State the hypotheses\n\n.eq\\[ $$\\small{H_0: \\beta_j = 0 \\text{ vs. }H_a: \\beta_j \\neq 0}$$\\]\n\n<br>\n\n2️⃣ Calculate the test statistic.\n\n.eq\\[ $$\\small{t = \\frac{\\hat{\\beta}_j - 0}{SE_{\\hat{\\beta}_j}} = \\frac{\\hat{\\beta}_j - 0}{\\hat{\\sigma}\\sqrt{\\frac{1}{(n-1)s_{x_j}^2}}}}$$\\] \\]\n\n.pull-right\\[ 3️⃣ Calculate the p-value.\n\n.eq\\[ $$\\text{p-value} = 2P(T > |t|) \\hspace{4mm} T \\sim t_{n-p-1}$$\\]\n\n<br>\n\n4️⃣ State the conclusion in context of the data.\n\n.eq\\[ Reject $H_0$ if p-value is sufficiently small.\\]\n\n\\]\n\n------------------------------------------------------------------------\n\n## Confidence intervals\n\n.eq\\[ The $C$% confidence confidence interval for $\\beta_j$ is\n\n$$\\begin{align}&\\hat{\\beta}_j \\pm t^* \\times SE_{\\hat{\\beta}_j}\\\\[8pt]\n&\\hat{\\beta}_j \\pm t^* \\times \\hat{\\sigma}\\sqrt{\\frac{1}{(n-1)s_{x_{j}}^2}}\\end{align}$$ where the critical value $t^* \\sim t(n-p-1)$ \\]\n\n**General interpretation:** We are $C$% confident that for every one unit increase in $x_j$, the response is expected to change by LB to UB units, holding all else constant.\n\n------------------------------------------------------------------------\n\n## Inference Activity (\\~8 minutes)\n\n-   Use the Model 3 output on the next slide to conduct a hypothesis test and interpret the 95% confidence interval for your assigned variable.\n\n    -   You do not have to do the calculations by hand.\n\n-   Choose one person to write your group's response on your slide [slide](https://docs.google.com/presentation/d/14WD6HUhUL4Z_i9tcG94tgfa9VbpDbAYkzprhAPB7O0w/edit?usp=sharing).\n\n-   Choose on person to share your group's responses with the class.\n\n------------------------------------------------------------------------\n\n## Model 3 output\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term                  | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:---------------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)           |   52.387|     0.200|   262.350|   0.000|   51.991|    52.782|\n|starters              |   -0.003|     0.016|    -0.189|   0.850|   -0.035|     0.029|\n|yearnew               |    0.020|     0.003|     7.576|   0.000|    0.014|     0.025|\n|conditiongood         |   -1.070|     0.423|    -2.527|   0.013|   -1.908|    -0.231|\n|conditionslow         |   -2.183|     0.270|    -8.097|   0.000|   -2.717|    -1.649|\n|yearnew:conditiongood |    0.012|     0.008|     1.598|   0.113|   -0.003|     0.027|\n|yearnew:conditionslow |    0.012|     0.004|     2.866|   0.005|    0.004|     0.020|\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Additional review topics\n\n-   [Uncertainty in predictions](https://sta210-fa21.netlify.app/slides/07-slr-prediction.html#1)\n\n-   [Variable transformations](https://sta210-fa21.netlify.app/slides/14-transformations.html#1)\n\n-   [Comparing models using Nested F tests](https://sta210-fa21.netlify.app/slides/15-model-comparison.html#1)\n\n------------------------------------------------------------------------\n\n## Acknowledgements\n\nThese slides are based on content in [BMLR: Chapter 1 - Review of Multiple Linear Regression](https://bookdown.org/roback/bookdown-BeyondMLR/ch-MLRreview.html)\n",
    "supporting": [
      "02-mlr-review-pt1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/panelset-0.2.6/panelset.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/panelset-0.2.6/panelset.js\"></script>\n<link href=\"../site_libs/countdown-0.4.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/countdown-0.4.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}