{
  "hash": "0b6a8a9241c46a6f452b9ac989f43898",
  "result": {
    "markdown": "---\ntitle: \"LR: Inference + conditions\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"2023-11-13\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 STA 210 - Fall 2023 -  Schedule](https://sta210-fa23.netlify.app/schedule)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false \n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  warning: false\n  message: false\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n\n## Announcements {.midi}\n\n-   Due dates\n\n    -   Draft report due in GitHub repo on 9am on the day of your lab\n\n    -   HW 04 due Wed, Nov 15 at 11:59pm\n\n    -   Statistics experience due Mon, Nov 20 at 11:59pm\n\n-   Next week:\n\n    -   (Optional) Project meetings Nov 20 & 21. [Click here](https://docs.google.com/spreadsheets/d/1EpTge-O1hBDnNy5KW7Y1FoNzIhpLoz4_Xx_nf_FbPgI/edit?usp=sharing) to sign up. Must sign up by Fri, Nov 17\n\n    -   No lecture Mon, Nov 20\n\n    -   No lab Tue, Nov 21\n\n    -   Thanksgiving Break: Wed, Nov 22 - Fri, Nov 24\n\n## Statistician of the day - **Alejandra Castillo** {.small}\n\n::: columns\n::: {.column width=\"60%\"}\nAlejandra Castillo did her undergraduate work at Pomona College in Mathematics and her MS (2019) and PhD (2023) at Oregon State University in Statistics.\n\nDr. Castillo's research lies at the intersection of unsupervised learning, dimension reduction, and inference, with applications in clinical trial design. Some of her work explores how to use baseline demographic information collected before randomization to a clinical trial, particularly as the baseline information changes during the course of the trial.\n:::\n\n::: {.column width=\"40%\"}\n![](images/statistician-of-the-day/castillo.jpg){fig-alt=\"Picture of Alejandra Castillo\" fig-align=\"center\"}\n:::\n:::\n\nMS Thesis: Castillo A. [On the Use of Baseline Values in Randomized Clinical Trials](https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/vq27zv110), MS Thesis, Oregon State, 2019.\n\nSource: [hardin47.github.io/CURV/scholars/castillo](https://hardin47.github.io/CURV/scholars/castillo.html)\n\n## Topics\n\n::: nonincremental\n-   Estimating coefficients in logistic regression\n-   Inference for coefficients in logistic regression\n-   Checking model conditions for logistic regression\n:::\n\n## Computational setup\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(openintro)\nlibrary(knitr)\nlibrary(kableExtra)  # for table embellishments\nlibrary(Stat2Data)   # for empirical logit\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_bw(base_size = 20))\n```\n:::\n\n\n# Data\n\n## Risk of coronary heart disease {.midi}\n\nThis data set is from an ongoing cardiovascular study on residents of the town of Framingham, Massachusetts. We want to examine the relationship between various health characteristics and the risk of having heart disease.\n\n-   `high_risk`:\n\n    -   1: High risk of having heart disease in next 10 years\n    -   0: Not high risk of having heart disease in next 10 years\n\n-   `age`: Age at exam time (in years)\n\n-   `education`: 1 = Some High School, 2 = High School or GED, 3 = Some College or Vocational School, 4 = College\n\n-   `currentSmoker`: 0 = nonsmoker, 1 = smoker\n\n## Data prep\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease <- read_csv(here::here(\"slides\", \"data/framingham.csv\")) |>\n  select(age, education, TenYearCHD, totChol, currentSmoker) |>\n  drop_na() |>\n  mutate(\n    high_risk = as.factor(TenYearCHD),\n    education = as.factor(education),\n    currentSmoker = as.factor(currentSmoker)\n  )\n\nheart_disease\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4,086 × 6\n     age education TenYearCHD totChol currentSmoker high_risk\n   <dbl> <fct>          <dbl>   <dbl> <fct>         <fct>    \n 1    39 4                  0     195 0             0        \n 2    46 2                  0     250 0             0        \n 3    48 1                  0     245 1             0        \n 4    61 3                  1     225 1             1        \n 5    46 3                  0     285 1             0        \n 6    43 2                  0     228 0             0        \n 7    63 1                  1     205 0             1        \n 8    45 2                  0     313 1             0        \n 9    52 1                  0     260 0             0        \n10    43 1                  0     225 1             0        \n# ℹ 4,076 more rows\n```\n:::\n:::\n\n\n# Estimating coefficients\n\n## Statistical model {.midi}\n\nThe form of the statistical model for logistic regression is\n\n$$\n\\log\\Big(\\frac{\\pi}{1-\\pi}\\Big) = \\beta_0 + \\beta_1X_1 + \\beta_2X_2 + \\dots + \\beta_pX_p\n$$\n\nwhere $\\pi$ is the probability $Y = 1$.\n\n. . .\n\nNotice there is no error term when writing the statistical model for logistic regression. Why?\n\n-   Recall that the statistical model is the \"data-generating\" model\n-   Each individual observed $Y$ is generated from a Bernoulli distribution, $Bernoulli(\\pi)$ (similarly we can think of $n$ observed $Y$'s as generated from a Binomial distribution, $Binomial(n,p)$)\n-   Therefore, the randomness is not produced by an error term but rather in the distribution used to generate $Y$\n\n## Estimating coefficients {.midi}\n\nRecall the log likelihood function\n\n$$\n\\log L = \\sum\\limits_{i=1}^n[y_i \\log(\\hat{\\pi}_i) + (1 - y_i)\\log(1 - \\hat{\\pi}_i)]\n$$\n\nwhere\n\n$\\hat{\\pi} = \\frac{exp\\{\\hat{\\beta}_0 + \\hat{\\beta}_1X_1 + \\dots + \\hat{\\beta}_pX_p\\}}{1 + exp\\{\\hat{\\beta}_0 + \\hat{\\beta}_1X_1 + \\dots + \\hat{\\beta}_pX_p\\}}$\n\n. . .\n\n-   The coefficients $\\hat{\\beta}_0, \\ldots, \\hat{\\beta}_p$ are estimated using maximum likelihood estimation\n\n-   Basic idea: Find the values of $\\hat{\\beta}_0, \\ldots, \\hat{\\beta}_p$ that give the observed data the maximum probability of occurring\n\n# Application exercise\n\n::: appex\n📋 [AE 15: Inference for Logistic Regression](../ae/ae-15-logistic-inference.html)\n:::\n\n# Inference for coefficients\n\n## Modeling risk of coronary heart disease\n\nUsing `age` and `education`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrisk_fit <- logistic_reg() |>\n  set_engine(\"glm\") |>\n  fit(high_risk ~ age + education, \n      data = heart_disease, family = \"binomial\")\n```\n:::\n\n\n## Model output {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(risk_fit, conf.int = TRUE) |> \n  kable(format = \"markdown\", digits = 3)\n```\n\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) |   -5.508|     0.311|   -17.692|   0.000|   -6.125|    -4.904|\n|age         |    0.076|     0.006|    13.648|   0.000|    0.065|     0.087|\n|education2  |   -0.245|     0.113|    -2.172|   0.030|   -0.469|    -0.026|\n|education3  |   -0.236|     0.135|    -1.753|   0.080|   -0.504|     0.024|\n|education4  |   -0.024|     0.150|    -0.161|   0.872|   -0.323|     0.264|\n:::\n:::\n\n\n$$\n\\small{\\log\\Big(\\frac{\\hat{\\pi}}{1-\\hat{\\pi}}\\Big) = -5.508 + 0.076 ~ \\text{age} - 0.245 ~ \\text{ed2} - 0.236 ~ \\text{ed3} - 0.024 ~ \\text{ed4}}\n$$\n\n## Inference for coefficients\n\nThere are two approaches for testing coefficients in logistic regression\n\n-   **Drop-in-deviance test**. Use to test...\n\n    -   a single coefficient\n    -   a categorical predictor with 3+ levels\n    -   a group of predictor variables\n\n-   **(Wald) hypothesis test.** Use to test\n\n    -   a single coefficient\n\n## Hypothesis test for $\\beta_j$\n\n**Hypotheses:** $H_0: \\beta_j = 0 \\hspace{2mm} \\text{ vs } \\hspace{2mm} H_a: \\beta_j \\neq 0$, given the other variables in the model\n\n. . .\n\n**Test Statistic:** $$z = \\frac{\\hat{\\beta}_j - 0}{SE_{\\hat{\\beta}_j}}$$\n\n. . .\n\n**P-value:** $P(|Z| > |z|)$, where $Z \\sim N(0, 1)$, the Standard Normal distribution\n\n## Confidence interval for $\\beta_j$\n\nWe can calculate the **C% confidence interval** for $\\beta_j$ as the following:\n\n$$\n\\Large{\\hat{\\beta}_j \\pm z^* SE_{\\hat{\\beta}_j}}\n$$\n\nwhere $z^*$ is calculated from the $N(0,1)$ distribution\n\n. . .\n\n::: callout-note\nThis is an interval for the change in the log-odds for every one unit increase in $x_j$\n:::\n\n## Interpretation in terms of the odds\n\nThe change in **odds** for every one unit increase in $x_j$.\n\n$$\n\\Large{exp\\{\\hat{\\beta}_j \\pm z^* SE_{\\hat{\\beta}_j}\\}}\n$$\n\n. . .\n\n**Interpretation:** We are $C\\%$ confident that for every one unit increase in $x_j$, the odds multiply by a factor of $exp\\{\\hat{\\beta}_j - z^* SE_{\\hat{\\beta}_j}\\}$ to $exp\\{\\hat{\\beta}_j + z^* SE_{\\hat{\\beta}_j}\\}$, holding all else constant.\n\n## Coefficient for `age` {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n   <th style=\"text-align:right;\"> conf.low </th>\n   <th style=\"text-align:right;\"> conf.high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -5.508 </td>\n   <td style=\"text-align:right;\"> 0.311 </td>\n   <td style=\"text-align:right;\"> -17.692 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -6.125 </td>\n   <td style=\"text-align:right;\"> -4.904 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: #D9E3E4 !important;\"> age </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.076 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.006 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 13.648 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.000 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.065 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.087 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education2 </td>\n   <td style=\"text-align:right;\"> -0.245 </td>\n   <td style=\"text-align:right;\"> 0.113 </td>\n   <td style=\"text-align:right;\"> -2.172 </td>\n   <td style=\"text-align:right;\"> 0.030 </td>\n   <td style=\"text-align:right;\"> -0.469 </td>\n   <td style=\"text-align:right;\"> -0.026 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education3 </td>\n   <td style=\"text-align:right;\"> -0.236 </td>\n   <td style=\"text-align:right;\"> 0.135 </td>\n   <td style=\"text-align:right;\"> -1.753 </td>\n   <td style=\"text-align:right;\"> 0.080 </td>\n   <td style=\"text-align:right;\"> -0.504 </td>\n   <td style=\"text-align:right;\"> 0.024 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education4 </td>\n   <td style=\"text-align:right;\"> -0.024 </td>\n   <td style=\"text-align:right;\"> 0.150 </td>\n   <td style=\"text-align:right;\"> -0.161 </td>\n   <td style=\"text-align:right;\"> 0.872 </td>\n   <td style=\"text-align:right;\"> -0.323 </td>\n   <td style=\"text-align:right;\"> 0.264 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n. . .\n\n**Hypotheses:**\n\n$$\nH_0: \\beta_{age} = 0 \\hspace{2mm} \\text{ vs } \\hspace{2mm} H_a: \\beta_{age} \\neq 0\n$$, given education is in the model\n\n## Coefficient for `age` {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n   <th style=\"text-align:right;\"> conf.low </th>\n   <th style=\"text-align:right;\"> conf.high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -5.508 </td>\n   <td style=\"text-align:right;\"> 0.311 </td>\n   <td style=\"text-align:right;\"> -17.692 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -6.125 </td>\n   <td style=\"text-align:right;\"> -4.904 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: #D9E3E4 !important;\"> age </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.076 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.006 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 13.648 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.000 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.065 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.087 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education2 </td>\n   <td style=\"text-align:right;\"> -0.245 </td>\n   <td style=\"text-align:right;\"> 0.113 </td>\n   <td style=\"text-align:right;\"> -2.172 </td>\n   <td style=\"text-align:right;\"> 0.030 </td>\n   <td style=\"text-align:right;\"> -0.469 </td>\n   <td style=\"text-align:right;\"> -0.026 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education3 </td>\n   <td style=\"text-align:right;\"> -0.236 </td>\n   <td style=\"text-align:right;\"> 0.135 </td>\n   <td style=\"text-align:right;\"> -1.753 </td>\n   <td style=\"text-align:right;\"> 0.080 </td>\n   <td style=\"text-align:right;\"> -0.504 </td>\n   <td style=\"text-align:right;\"> 0.024 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education4 </td>\n   <td style=\"text-align:right;\"> -0.024 </td>\n   <td style=\"text-align:right;\"> 0.150 </td>\n   <td style=\"text-align:right;\"> -0.161 </td>\n   <td style=\"text-align:right;\"> 0.872 </td>\n   <td style=\"text-align:right;\"> -0.323 </td>\n   <td style=\"text-align:right;\"> 0.264 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**Test statistic:**\n\n$$z = \\frac{0.07559 - 0}{0.00554} = 13.64\n$$\n\n## Coefficient for `age` {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n   <th style=\"text-align:right;\"> conf.low </th>\n   <th style=\"text-align:right;\"> conf.high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -5.508 </td>\n   <td style=\"text-align:right;\"> 0.311 </td>\n   <td style=\"text-align:right;\"> -17.692 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -6.125 </td>\n   <td style=\"text-align:right;\"> -4.904 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: #D9E3E4 !important;\"> age </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.076 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.006 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 13.648 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.000 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.065 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.087 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education2 </td>\n   <td style=\"text-align:right;\"> -0.245 </td>\n   <td style=\"text-align:right;\"> 0.113 </td>\n   <td style=\"text-align:right;\"> -2.172 </td>\n   <td style=\"text-align:right;\"> 0.030 </td>\n   <td style=\"text-align:right;\"> -0.469 </td>\n   <td style=\"text-align:right;\"> -0.026 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education3 </td>\n   <td style=\"text-align:right;\"> -0.236 </td>\n   <td style=\"text-align:right;\"> 0.135 </td>\n   <td style=\"text-align:right;\"> -1.753 </td>\n   <td style=\"text-align:right;\"> 0.080 </td>\n   <td style=\"text-align:right;\"> -0.504 </td>\n   <td style=\"text-align:right;\"> 0.024 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education4 </td>\n   <td style=\"text-align:right;\"> -0.024 </td>\n   <td style=\"text-align:right;\"> 0.150 </td>\n   <td style=\"text-align:right;\"> -0.161 </td>\n   <td style=\"text-align:right;\"> 0.872 </td>\n   <td style=\"text-align:right;\"> -0.323 </td>\n   <td style=\"text-align:right;\"> 0.264 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**P-value:**\n\n$$\nP(|Z| > |13.64|) \\approx 0\n$$\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n2 * pnorm(13.64,lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.315606e-42\n```\n:::\n:::\n\n\n## Coefficient for `age` {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n   <th style=\"text-align:right;\"> conf.low </th>\n   <th style=\"text-align:right;\"> conf.high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -5.508 </td>\n   <td style=\"text-align:right;\"> 0.311 </td>\n   <td style=\"text-align:right;\"> -17.692 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -6.125 </td>\n   <td style=\"text-align:right;\"> -4.904 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: #D9E3E4 !important;\"> age </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.076 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.006 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 13.648 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.000 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.065 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.087 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education2 </td>\n   <td style=\"text-align:right;\"> -0.245 </td>\n   <td style=\"text-align:right;\"> 0.113 </td>\n   <td style=\"text-align:right;\"> -2.172 </td>\n   <td style=\"text-align:right;\"> 0.030 </td>\n   <td style=\"text-align:right;\"> -0.469 </td>\n   <td style=\"text-align:right;\"> -0.026 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education3 </td>\n   <td style=\"text-align:right;\"> -0.236 </td>\n   <td style=\"text-align:right;\"> 0.135 </td>\n   <td style=\"text-align:right;\"> -1.753 </td>\n   <td style=\"text-align:right;\"> 0.080 </td>\n   <td style=\"text-align:right;\"> -0.504 </td>\n   <td style=\"text-align:right;\"> 0.024 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education4 </td>\n   <td style=\"text-align:right;\"> -0.024 </td>\n   <td style=\"text-align:right;\"> 0.150 </td>\n   <td style=\"text-align:right;\"> -0.161 </td>\n   <td style=\"text-align:right;\"> 0.872 </td>\n   <td style=\"text-align:right;\"> -0.323 </td>\n   <td style=\"text-align:right;\"> 0.264 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**Conclusion:**\n\nThe p-value is very small, so we reject $H_0$. The data provide sufficient evidence that age is a statistically significant predictor of whether someone is high risk of having heart disease, after accounting for education.\n\n## CI for `age`\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n   <th style=\"text-align:right;\"> conf.low </th>\n   <th style=\"text-align:right;\"> conf.high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -5.508 </td>\n   <td style=\"text-align:right;\"> 0.311 </td>\n   <td style=\"text-align:right;\"> -17.692 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -6.125 </td>\n   <td style=\"text-align:right;\"> -4.904 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: #D9E3E4 !important;\"> age </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.076 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.006 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 13.648 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.000 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.065 </td>\n   <td style=\"text-align:right;background-color: #D9E3E4 !important;\"> 0.087 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education2 </td>\n   <td style=\"text-align:right;\"> -0.245 </td>\n   <td style=\"text-align:right;\"> 0.113 </td>\n   <td style=\"text-align:right;\"> -2.172 </td>\n   <td style=\"text-align:right;\"> 0.030 </td>\n   <td style=\"text-align:right;\"> -0.469 </td>\n   <td style=\"text-align:right;\"> -0.026 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education3 </td>\n   <td style=\"text-align:right;\"> -0.236 </td>\n   <td style=\"text-align:right;\"> 0.135 </td>\n   <td style=\"text-align:right;\"> -1.753 </td>\n   <td style=\"text-align:right;\"> 0.080 </td>\n   <td style=\"text-align:right;\"> -0.504 </td>\n   <td style=\"text-align:right;\"> 0.024 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education4 </td>\n   <td style=\"text-align:right;\"> -0.024 </td>\n   <td style=\"text-align:right;\"> 0.150 </td>\n   <td style=\"text-align:right;\"> -0.161 </td>\n   <td style=\"text-align:right;\"> 0.872 </td>\n   <td style=\"text-align:right;\"> -0.323 </td>\n   <td style=\"text-align:right;\"> 0.264 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n::: question\nInterpret the 95% confidence interval for `age` in terms of the **odds** of being high risk for heart disease.\n:::\n\n# Application exercise\n\n::: appex\n📋 [AE 15: Inference for Logistic Regression](../ae/ae-15-logistic-inference.html)\n:::\n\n# Conditions\n\n## The model {.smaller}\n\nLet's predict `high_risk` from age, total cholesterol, and whether the patient is a current smoker:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrisk_fit <- logistic_reg() |>\n  set_engine(\"glm\") |>\n  fit(high_risk ~ age + totChol + currentSmoker, \n      data = heart_disease, family = \"binomial\")\n\ntidy(risk_fit, conf.int = TRUE) |> \n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n   <th style=\"text-align:right;\"> conf.low </th>\n   <th style=\"text-align:right;\"> conf.high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -6.673 </td>\n   <td style=\"text-align:right;\"> 0.378 </td>\n   <td style=\"text-align:right;\"> -17.647 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -7.423 </td>\n   <td style=\"text-align:right;\"> -5.940 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> age </td>\n   <td style=\"text-align:right;\"> 0.082 </td>\n   <td style=\"text-align:right;\"> 0.006 </td>\n   <td style=\"text-align:right;\"> 14.344 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 0.071 </td>\n   <td style=\"text-align:right;\"> 0.094 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> totChol </td>\n   <td style=\"text-align:right;\"> 0.002 </td>\n   <td style=\"text-align:right;\"> 0.001 </td>\n   <td style=\"text-align:right;\"> 1.940 </td>\n   <td style=\"text-align:right;\"> 0.052 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 0.004 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> currentSmoker1 </td>\n   <td style=\"text-align:right;\"> 0.443 </td>\n   <td style=\"text-align:right;\"> 0.094 </td>\n   <td style=\"text-align:right;\"> 4.733 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 0.260 </td>\n   <td style=\"text-align:right;\"> 0.627 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Conditions for logistic regression\n\n1.  **Linearity:** The log-odds have a linear relationship with the predictors.\n\n2.  **Randomness:** The data were obtained from a random process\n\n3.  **Independence:** The observations are independent from one another.\n\n## Empirical logit\n\nThe **empirical logit** is the log of the observed odds:\n\n$$\n\\text{logit}(\\hat{p}) = \\log\\Big(\\frac{\\hat{p}}{1 - \\hat{p}}\\Big) = \\log\\Big(\\frac{\\# \\text{Yes}}{\\# \\text{No}}\\Big)\n$$\n\n## Calculating empirical logit (categorical predictor)\n\nIf the predictor is categorical, we can calculate the empirical logit for each level of the predictor.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease |>\n  count(currentSmoker, high_risk) |>\n  group_by(currentSmoker) |>\n  mutate(prop = n/sum(n)) |>\n  filter(high_risk == \"1\") |>\n  mutate(emp_logit = log(prop/(1-prop)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n# Groups:   currentSmoker [2]\n  currentSmoker high_risk     n  prop emp_logit\n  <fct>         <fct>     <int> <dbl>     <dbl>\n1 0             1           301 0.145     -1.77\n2 1             1           318 0.158     -1.67\n```\n:::\n:::\n\n\n## Calculating empirical logit (quantitative predictor)\n\n1.  Divide the range of the predictor into intervals with approximately equal number of cases. (If you have enough observations, use 5 - 10 intervals.)\n\n2.  Compute the empirical logit for each interval\n\n. . .\n\nYou can then calculate the mean value of the predictor in each interval and create a plot of the empirical logit versus the mean value of the predictor in each interval.\n\n## Empirical logit plot in R (quantitative predictor)\n\nCreated using `dplyr` and `ggplot` functions.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](20-logistic-inf_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Empirical logit plot in R (quantitative predictor)\n\nCreated using `dplyr` and `ggplot` functions.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease |> \n  mutate(age_bin = cut_interval(age, n = 10)) |>\n  group_by(age_bin) |>\n  mutate(mean_age = mean(age)) |>\n  count(mean_age, high_risk) |>\n  mutate(prop = n/sum(n)) |>\n  filter(high_risk == \"1\") |>\n  mutate(emp_logit = log(prop/(1-prop))) |>\n  ggplot(aes(x = mean_age, y = emp_logit)) + \n  geom_point() + \n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(x = \"Mean Age\", \n       y = \"Empirical logit\")\n```\n:::\n\n\n## Empirical logit plot in R (quantitative predictor)\n\nUsing the `emplogitplot1` function from the **Stat2Data** R package\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemplogitplot1(high_risk ~ age, \n              data = heart_disease, \n              ngroups = 10)\n```\n\n::: {.cell-output-display}\n![](20-logistic-inf_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Empirical logit plot in R (interactions)\n\nUsing the `emplogitplot2` function from the **Stat2Data** R package\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemplogitplot2(high_risk ~ age + currentSmoker, data = heart_disease, \n              ngroups = 10, \n              putlegend = \"bottomright\")\n```\n\n::: {.cell-output-display}\n![](20-logistic-inf_files/figure-revealjs/unnamed-chunk-17-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Checking linearity\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemplogitplot1(high_risk ~ age, \n              data = heart_disease, \n              ngroups = 10)\n```\n\n::: {.cell-output-display}\n![](20-logistic-inf_files/figure-revealjs/unnamed-chunk-18-1.png){fig-align='center' width=90%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemplogitplot1(high_risk ~ totChol, \n              data = heart_disease, \n              ngroups = 10)\n```\n\n::: {.cell-output-display}\n![](20-logistic-inf_files/figure-revealjs/unnamed-chunk-19-1.png){fig-align='center' width=90%}\n:::\n:::\n\n:::\n:::\n\n. . .\n\n✅ The linearity condition is satisfied. There is a linear relationship between the empirical logit and the predictor variables.\n\n## Checking randomness\n\nWe can check the randomness condition based on the context of the data and how the observations were collected.\n\n-   Was the sample randomly selected?\n-   If the sample was not randomly selected, ask whether there is reason to believe the observations in the sample differ systematically from the population of interest.\n\n. . .\n\n✅ The randomness condition is satisfied. We do not have reason to believe that the participants in this study differ systematically from adults in the U.S. in regards to health characteristics and risk of heart disease.\n\n## Checking independence\n\n-   We can check the independence condition based on the context of the data and how the observations were collected.\n-   Independence is most often violated if the data were collected over time or there is a strong spatial relationship between the observations.\n\n. . .\n\n✅ The independence condition is satisfied. It is reasonable to conclude that the participants' health characteristics are independent of one another.\n",
    "supporting": [
      "20-logistic-inf_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}