{
  "hash": "5aee3c420899a179190867bd06567205",
  "result": {
    "markdown": "---\ntitle: \"Logistic regression\"\nsubtitle: \"Binomial responses + overdispersion\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"February 7, 2024\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 STA 310 - Spring 2024](https://sta310-sp24.netlify.app)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    slide-number: true\n    multiplex: false\n    transition: fade\n    incremental: false \n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  warning: false\n  message: false\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n## Announcements\n\n-   HW 02 due TODAY at 11:59pm\n\n-   Project 01\n\n    -   presentations in class Wed, Feb 14\n\n    -   write up due Thu, Feb 15 at noon\n\n## Learning goals\n\n-   Visualizations for logistic regression\n\n-   Fit and interpret logistic regression model for binomial response variable\n\n-   Explore diagnostics for logistic regression\n\n-   Summarize GLMs for independent observations\n\n::: aside\nNotes based on Chapter 6 @roback2021beyond unless noted otherwise.\n:::\n\n# Logistic regression\n\n## Bernoulli + Binomial random variables {.small}\n\nLogistic regression is used to analyze data with two types of responses:\n\n-   **Bernoulli (Binary)**: These responses take on two values success $(Y = 1)$ or failure $(Y = 0)$, yes $(Y = 1)$ or no $(Y = 0)$, etc.\n\n$$P(Y = y) = p^y(1-p)^{1-y} \\hspace{10mm} y = 0, 1$$\n\n-   **Binomial**: Number of successes in a Bernoulli process, $n$ independent trials with a constant probability of success $p$.\n\n$$P(Y = y) = {n \\choose y}p^{y}(1-p)^{n - y} \\hspace{10mm} y = 0, 1, \\ldots, n$$\n\n. . .\n\nIn both instances, the goal is to model $p$ the probability of success.\n\n## Logistic regression model {.midi}\n\n$$\n\\log\\Big(\\frac{p}{1-p}\\Big) = \\beta_0 + \\beta_1x_1 + \\beta_2x_2 + \\dots + \\beta_px_p\n$$\n\n-   The response variable, $\\log\\Big(\\frac{p}{1-p}\\Big)$, is the log(odds) of success, i.e. the logit\n-   Use the model to calculate the probability of success $$\\hat{p} = \\frac{e^{\\beta_0 + \\beta_1x_1 + \\beta_2x_2 + \\dots + \\beta_px_p}}{1 + e^{\\beta_0 + \\beta_1x_1 + \\beta_2x_2 + \\dots + \\beta_px_p}}$$\n-   When the response is a Bernoulli random variable, the probabilities can be used to classify each observation as a success or failure\n\n## Interpreting coefficients\n\n$$\n\\log\\Big(\\frac{\\hat{p}}{1-\\hat{p}}\\Big) = \\hat{\\beta}_0 + \\hat{\\beta}_1x_1 + \\hat{\\beta}_2x_2 + \\dots + \\hat{\\beta}_px_p\n$$\n\n-   $\\hat{\\beta}_j$ is predicted change in the log-odds when going from $x_j$ to $x_j + 1$, holding all else constant\n\n-   $e^{\\beta_j}$ is the predicted change the odds when going from $x_j$ to $x_j + 1$, holding all else constant (**odds ratio)**\n\n## COVID-19 infection prevention practices at food establishments\n\nResearchers at Wollo Univeristy in Ethiopia conducted a study in July and August 2020 to understand factors associated with good COVID-19 infection prevention practices at food establishments. Their study is published in @andualem2022covid .\n\n<br>\n\nThey were particularly interested in the understanding implementation of prevention practices at food establishments, given the workers' increased risk due to daily contact with customers.\n\n## Results\n\n![](images/07/logistic-output.PNG){fig-align=\"center\"}\n\n## Interpretation\n\n::: incremental\n-   The (adjusted) odds ratio for availability of COVID-19 infection prevention guidelines is 2.68 with 95% CI (1.52, 4.75).\n\n-   The odds ratio between workers at a restaurant with such guidelines and those at a restaurant without the guidelines is 2.68, after adjusting for the other factors.\n\n-   **Interpretation**: The odds a worker at a restaurant with COVID-19 infection prevention guidelines uses good infection prevention practices is 2.68 times the odds of a worker at a restaurant without the guidelines, holding all other factors constant.\n:::\n\n# Visualizations for logistic regression\n\n## Access to personal protective equipment {.midi}\n\nWe will use the data from @andualem2022covid to explore the association between age, sex, years of service, and whether someone works at a food establishment with access to personal protective equipment (PPE) as of August 2020. We will use access to PPE as a proxy for wearing PPE.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n| age|sex    | years| ppe_access|\n|---:|:------|-----:|----------:|\n|  34|Male   |     2|          1|\n|  32|Female |     3|          1|\n|  32|Female |     1|          1|\n|  40|Male   |     4|          1|\n|  32|Male   |    10|          1|\n:::\n:::\n\n\n## EDA for binary response\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(Stat2Data)\npar(mfrow = c(1, 2))\nemplogitplot1(ppe_access ~ age, data = covid_df, ngroups = 10)\nemplogitplot1(ppe_access ~ years, data = covid_df, ngroups = 5)\n```\n\n::: {.cell-output-display}\n![](08-logistic-pt2_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## EDA for binary response\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(viridis)\nggplot(data = covid_df, aes(x = sex, fill = factor(ppe_access))) + \n  geom_bar(position = \"fill\")  +\n  labs(x = \"Sex\", \n       fill = \"PPE Access\", \n       title = \"PPE Access by Sex\") + \n  scale_fill_viridis_d()\n```\n\n::: {.cell-output-display}\n![](08-logistic-pt2_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## Model results {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nppe_model <- glm(factor(ppe_access) ~ age + sex + years, \n                 data = covid_df, family = binomial)\ntidy(ppe_model, conf.int = TRUE) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) |   -2.127|     0.458|    -4.641|   0.000|   -3.058|    -1.257|\n|age         |    0.056|     0.017|     3.210|   0.001|    0.023|     0.091|\n|sexMale     |    0.341|     0.224|     1.524|   0.128|   -0.098|     0.780|\n|years       |    0.264|     0.066|     4.010|   0.000|    0.143|     0.401|\n:::\n:::\n\n\n## Visualizing coefficient estimates {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel_odds_ratios <- tidy(ppe_model, exponentiate = TRUE, conf.int = TRUE)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = model_odds_ratios, aes(x = term, y = estimate)) +\n  geom_point() +\n  geom_hline(yintercept = 1, lty = 2) + \n  geom_pointrange(aes(ymin = conf.low, ymax = conf.high))+\n  labs(title = \"Adjusted odds ratios\",\n       x = \"\",\n       y = \"Estimated AOR\") +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](08-logistic-pt2_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=55%}\n:::\n:::\n\n\n# Logistic regression for binomial response variable\n\n## Data: Supporting railroads in the 1870s {.midi}\n\nThe data set [`RR_Data_Hale.csv`](data/RR_Data_Hale.csv) contains information on support for referendums related to railroad subsidies for 11 communities in Hale County, Alabama in the 1870s. The data were originally collected from the US Census by historian Michael Fitzgerald and analyzed as part of a thesis project by a student at St. Olaf College. The variables in the data are\n\n-   `pctBlack`: percentage of Black residents in the county\n-   `distance`: distance the proposed railroad is from the community (in miles)\n-   `YesVotes`: number of \"yes\" votes in favor of the proposed railroad line\n-   `NumVotes`: number of votes cast in the election\n\n. . .\n\n**Primary question**: Was voting on the railroad referendum related to the distance from the proposed railroad line, after adjusting for the demographics of a county?\n\n## The data {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrr <- read_csv(\"data/RR_Data_Hale.csv\")\nrr |> slice(1:5) |> kable()\n```\n\n::: {.cell-output-display}\n|County          | popBlack| popWhite| popTotal| pctBlack| distance| YesVotes| NumVotes|\n|:---------------|--------:|--------:|--------:|--------:|--------:|--------:|--------:|\n|Carthage        |      841|      599|     1440|    58.40|       17|       61|      110|\n|Cederville      |     1774|      146|     1920|    92.40|        7|        0|       15|\n|Five Mile Creek |      140|      626|      766|    18.28|       15|        4|       42|\n|Greensboro      |     1425|      975|     2400|    59.38|        0|     1790|     1804|\n|Harrison        |      443|      355|      798|    55.51|        7|        0|       15|\n:::\n:::\n\n\n## Exploratory data analysis\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrr <- rr |>\n  mutate(pctYes = YesVotes/NumVotes, \n         emp_logit = log(pctYes / (1 - pctYes)))\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-logistic-pt2_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## Exploratory data analysis\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrr <- rr |>\n  mutate(inFavor = if_else(pctYes > 0.5, \"Yes\", \"No\"))\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-logistic-pt2_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nCheck for potential multicollinearity and interaction effect.\n\n## Model {.midi}\n\nLet $p$ be the percent of yes votes in a county. We'll start by fitting the following model:\n\n$$\\log\\Big(\\frac{p}{1-p}\\Big)  = \\beta_0 + \\beta_1 ~ dist + \\beta_2 ~ pctBlack$$\n\n. . .\n\n**Likelihood**\n\n$$\\begin{aligned}L(p) &= \\prod_{i=1}^{n} {m_i \\choose y_i}p_i^{y_i}(1 - p_i)^{m_i - y_i} \\\\ \n&= \\prod_{i=1}^{n} {m_i \\choose y_i}\\Big[\\frac{e^{\\beta_0 + \\beta_1 ~ dist_i + \\beta_2 ~ pctBlack_i}}{1 + e^{\\beta_0 + \\beta_1 ~ dist_i + \\beta_2 ~ pctBlack_i}}\\Big]^{y_i}\\Big[\\frac{1}{e^{\\beta_0 + \\beta_1 ~ dist_i + \\beta_2 ~ pctBlack_i}}\\Big]^{m_i - y_i} \\\\\\end{aligned}$$\n\nUse IRLS to find $\\hat{\\beta}_0, \\hat{\\beta}_1, \\hat{\\beta}_2$.\n\n## Model in R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrr_model <- glm(cbind(YesVotes, NumVotes - YesVotes) ~ distance + pctBlack, \n                data = rr, family = binomial)\ntidy(rr_model, conf.int = TRUE) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) |    4.222|     0.297|    14.217|   0.000|    3.644|     4.809|\n|distance    |   -0.292|     0.013|   -22.270|   0.000|   -0.318|    -0.267|\n|pctBlack    |   -0.013|     0.004|    -3.394|   0.001|   -0.021|    -0.006|\n:::\n:::\n\n\n$$\\log\\Big(\\frac{\\hat{p}}{1-\\hat{p}}\\Big)  = 4.22 - 0.292 ~ dist - 0.013 ~ pctBlack$$\n\n# Application exercise\n\n::: appex\n📋 [sta310-sp24.netlify.app/ae/lec-08-logistic](https://sta310-sp24.netlify.app/ae/lec-08-logistic)\\\n\\\nPart 1\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div class=\"countdown\" id=\"timer_0a429523\" data-update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;margin:1.25%;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">10</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n:::\n:::\n\n\n## Residuals {.midi}\n\nSimilar to Poisson regression, there are two types of residuals: Pearson and deviance residuals\n\n. . .\n\n**Pearson residuals**\n\n$$\n\\text{Pearson residual}_i = \\frac{\\text{actual count} - \\text{predicted count}}{\\text{SD count}} = \\frac{Y_i - m_i\\hat{p}_i}{\\sqrt{m_i\\hat{p}_i(1 - \\hat{p}_i)}}\n$$\n\n. . .\n\n**Deviance residuals**\n\n$$\nd_i = \\text{sign}(Y_i - m_i\\hat{p}_i)\\sqrt{2\\Big[Y_i\\log\\Big(\\frac{Y_i}{m_i\\hat{p}_i}\\Big) + (m_i - Y_i)\\log\\Big(\\frac{m_i - Y_i}{m_i - m_i\\hat{p}_i}\\Big)\\Big]}\n$$\n\n## Plot of deviance residuals\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrr_int_aug <- augment(rr_int_model, type.predict = \"response\", \n                        type.residuals = \"deviance\")\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-logistic-pt2_files/figure-revealjs/unnamed-chunk-17-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## Goodness of fit {.midi}\n\nSimilar to Poisson regression, the sum of the squared deviance residuals is used to assess goodness of fit.\n\n$$\\begin{aligned} &H_0: \\text{ Model is a good fit} \\\\\n&H_a: \\text{ Model is not a good fit}\\end{aligned}$$\n\n. . .\n\n-   When $m_i$'s are large and the model is a good fit $(H_0 \\text{ true})$ the residual deviance follows a $\\chi^2$ distribution with $n - p$ degrees of freedom.\n    -   Recall $n - p$ is the residual degrees of freedom.\n\n. . .\n\n-   If the model fits, we expect the residual deviance to be approximately what value?\n\n# Overdispersion\n\n## Adjusting for overdispersion\n\n-   Overdispersion occurs when there is **extra-binomial variation**, i.e. the variance is greater than what we would expect, $np(1-p)$.\n\n-   Similar to Poisson regression, we can adjust for overdispersion in the binomial regression model by using a dispersion parameter $$\\hat{\\phi} = \\sum \\frac{(\\text{Pearson residuals})^2}{n-p}$$\n\n    -   By multiplying by $\\hat{\\phi}$, we are accounting for the reduction in information we would expect from independent observations.\n\n## Adjusting for overdispersion\n\n-   We adjust for overdispersion using a **quasibinomial** model.\n    -   \"Quasi\" reflects the fact we are no longer using a binomial model with true likelihood.\n-   The standard errors of the coefficients are $SE_{Q}(\\hat{\\beta}_j) = \\sqrt{\\hat{\\phi}} SE(\\hat{\\beta})$\n    -   Inference is done using the $t$ distribution to account for extra variability\n\n# Application exercise\n\n::: appex\n📋 [sta310-sp24.netlify.app/ae/lec-08-logistic](https://sta310-sp24.netlify.app/ae/lec-08-logistic)\\\n\\\nPart 2\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div class=\"countdown\" id=\"timer_c0319c88\" data-update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;margin:1.25%;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">06</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n:::\n:::\n\n\n## References\n",
    "supporting": [
      "08-logistic-pt2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/countdown-0.4.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/countdown-0.4.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}