{
  "hash": "b29cfa19cd899f42989962b1d37582a1",
  "result": {
    "markdown": "---\ntitle: \"Poisson Regression\"\nsubtitle: \"Goodness-of-fit & overdispersion\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"2024-01-29\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 STA 310 - Spring 2024](https://sta310-sp24.netlify.app)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    slide-number: true\n    multiplex: false\n    transition: fade\n    incremental: false \n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  warning: false\n  message: false\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n## Announcements\n\n-   Quiz 01: Tue, Jan 29 \\~ 9am  - Thu, Jan 31 at noon\n\n    <!--add note about content + allowed resources-->\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n## Topics\n\n-   Define and calculate residuals for the Poisson regression model\n\n-   Use Goodness-of-fit to assess model fit\n\n-   Identify overdispersion\n\n-   Apply modeling approaches to deal with overdispersion\n\n    -   Quasi-Poisson\n\n    -   Negative binomial\n\n::: aside\nNotes based on Sections 4.4 and 4.9 of @roback2021beyond unless noted otherwise.\n:::\n\n## The data: Household size in the Philippines {.midi}\n\nThe data [fHH1.csv](data/fHH1.csv) come from the 2015 Family Income and Expenditure Survey conducted by the Philippine Statistics Authority.\n\n**Goal**: Understand the association between household size and various characteristics of the household\n\n**Response**:\n\n-   `total`: Number of people in the household other than the head\n\n::: columns\n::: {.column width=\"50%\"}\n**Predictors**:\n\n-   `location`: Where the house is located\n-   `age`: Age of the head of household\n-   `roof`: Type of roof on the residence (proxy for wealth)\n:::\n\n::: {.column width=\"50%\"}\n**Other variables**:\n\n-   `numLT5`: Number in the household under 5 years old\n:::\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n## Poisson regression model\n\nIf $Y_i \\sim Poisson$ with $\\lambda = \\lambda_i$ for the given values $x_{i1}, \\ldots, x_{ip}$, then\n\n$$\\log(\\lambda_i) = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\dots + \\beta_p x_{ip}$$\n\n. . .\n\n-   Each observation can have a different value of $\\lambda$ based on its value of the predictors $x_1, \\ldots, x_p$\n\n-   $\\lambda$ determines the mean and variance, so we don't need to estimate a separate error term\n\n## Household vs. Age\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhh_age <- glm(total ~ age, data = hh_data, family = poisson)\n\ntidy(hh_age) |> \n  kable(digits = 4)\n```\n\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   1.5499|    0.0503|   30.8290|       0|\n|age         |  -0.0047|    0.0009|   -5.0258|       0|\n:::\n:::\n\n\n$$\\log(\\hat{\\lambda}) = 1.5499  - 0.0047 ~ age$$\n\nThe mean household size is predicted to decrease by 0.47% (multiply by a factor of $e^{-0.0047}$) for each year older the head of the household is.\n\n## Household vs. age and location\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-poisson-pt2_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n::: aside\nVisualization recreated from [Figure 4.6](https://bookdown.org/roback/bookdown-BeyondMLR/ch-poissonreg.html#linear-least-squares-vs.-poisson-regression) in @roback2021beyond.\n:::\n\n## Add $age^2$ and $location$ to model?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhh_age_loc <- glm(total ~ age + I(age^2) + location, \n                  data = hh_data, family = poisson)\n```\n:::\n\n\n<br>\n\n. . .\n\n**Use Likelihood Ratio Test**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(hh_age, hh_age_loc, test = \"LRT\") |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n| Resid. Df| Resid. Dev| Df| Deviance| Pr(>Chi)|\n|---------:|----------:|--:|--------:|--------:|\n|      1498|   2337.089| NA|       NA|       NA|\n|      1493|   2187.800|  5|  149.289|        0|\n:::\n:::\n\n\n## Selected model {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term                 | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:--------------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)          |  -0.3843|    0.1821|   -2.1107|  0.0348|  -0.7444|   -0.0306|\n|age                  |   0.0704|    0.0069|   10.1900|  0.0000|   0.0569|    0.0840|\n|I(age^2)             |  -0.0007|    0.0001|  -10.9437|  0.0000|  -0.0008|   -0.0006|\n|locationDavaoRegion  |  -0.0194|    0.0538|   -0.3605|  0.7185|  -0.1250|    0.0859|\n|locationIlocosRegion |   0.0610|    0.0527|    1.1580|  0.2468|  -0.0423|    0.1641|\n|locationMetroManila  |   0.0545|    0.0472|    1.1542|  0.2484|  -0.0378|    0.1473|\n|locationVisayas      |   0.1121|    0.0417|    2.6853|  0.0072|   0.0308|    0.1945|\n:::\n:::\n\n\n. . .\n\n**Does this model sufficiently explain the variability in the mean household size?**\n\n# Goodness-of-fit\n\n## Pearson residuals {.midi}\n\nWe can calculate two types of residuals for Poisson regression: Pearson residuals and deviance residuals\\\n\\\n$$\\text{Pearson residual}_i = \\frac{\\text{observed} - \\text{predicted}}{\\text{std. error}} = \\frac{Y_i - \\hat{\\lambda}_i}{\\sqrt{\\hat{\\lambda}_i}}$$\n\n. . .\n\n-   Similar interpretation as standardized residuals from linear regression\n\n-   Expect most to fall between -2 and 2\n\n-   Used to calculate overdispersion parameter (more on this soon)\n\n## Deviance residuals {.small}\n\n-   The **deviance residual** describes how the observed data deviates from the fitted model $$\\text{deviance residual}_i = \\text{sign}(Y_i - \\hat{\\lambda}_i)\\sqrt{2\\Bigg[Y_i\\log\\bigg(\\frac{Y_i}{\\hat{\\lambda}_i}\\bigg) - (Y_i - \\hat{\\lambda}_i)\\Bigg]}$$\n\nwhere\n\n$$\\text{sign}(Y_i - \\hat{\\lambda}_i)  =  \\begin{cases}\n1 & \\text{ if }(Y_i - \\hat{\\lambda}_i) > 0 \\\\\n-1 & \\text{ if }(Y_i - \\hat{\\lambda}_i) < 0 \\\\\n0 & \\text{ if }(Y_i - \\hat{\\lambda}_i) = 0\n\\end{cases}$$\n\n-   Good fitting models $\\Rightarrow$ small deviances\n\n## Selected model: Residual plots\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhh_age_loc_aug_pearson <- augment(hh_age_loc, type.residuals = \"pearson\") \nhh_age_loc_aug_deviance <- augment(hh_age_loc, type.residuals = \"deviance\")\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-poisson-pt2_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## Goodness-of-fit {.small}\n\n-   **Goal**: Use the (residual) deviance to assess how much the predicted values differ from the observed values.\n\n    $$\n    \\text{deviance} = \\sum_{i=1}^{n}(\\text{deviance residual})_i^2\n    $$\n\n-   When a model is true, we expect\\\n    $$\\text{deviance} \\sim \\chi^2_{df}$$\n\nwhere $df$ is the model's residual degrees of freedom\n\n. . .\n\n-   **Question to answer**: What is the probability of observing a deviance larger than the one we've observed, given this model sufficiently fits the data?\n\n$$P(\\chi^2_{df} > \\text{ deviance})$$\n\n# Application exercise\n\n::: appex\n📋 [sta310-sp24.netlify.app/ae/lec-05-overdisp](../ae/lec-05-overdisp)\n:::\n\n## Goodness-of-fit calculations\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhh_age_loc$deviance\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2187.8\n```\n:::\n\n```{.r .cell-code}\nhh_age_loc$df.residual\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1493\n```\n:::\n:::\n\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npchisq(hh_age_loc$deviance, hh_age_loc$df.residual, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.153732e-29\n```\n:::\n:::\n\n\n<br>\n\n. . .\n\nThe probability of observing a deviance greater than 2187.8 is $\\approx 0$, so there is significant evidence of **lack-of-fit**.\n\n## Lack-of-fit\n\nThere are a few potential reasons for observing lack-of-fit:\n\n-   Missing important interactions or higher-order terms\n\n-   Missing important variables (perhaps this means a more comprehensive data set is required)\n\n-   There could be extreme observations causing the deviance to be larger than expected (assess based on the residual plots)\n\n-   There could be a problem with the Poisson model\n\n    -   Only one parameter $\\lambda$ to describe mean and variance\n\n    -   May need more flexibility in the model to handle **overdispersion**\n\n## Overdispersion\n\n**Overdispersion**: There is more variability in the response than what is implied by the Poisson model\n\n<br>\n\n::: columns\n::: {.column width=\"50%\"}\n<center><b>Overall</b></center>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|  mean|   var|\n|-----:|-----:|\n| 3.685| 5.534|\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n<center><b>by Location</b></center>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|location     |  mean|   var|\n|:------------|-----:|-----:|\n|CentralLuzon | 3.402| 4.152|\n|DavaoRegion  | 3.390| 4.723|\n|IlocosRegion | 3.586| 5.402|\n|MetroManila  | 3.707| 4.863|\n|Visayas      | 3.902| 6.602|\n:::\n:::\n\n:::\n:::\n\n## Why overdispersion matters\n\nIf there is overdispersion, then there is more variation in the response than what's implied by a Poisson model. This means\n\nThe standard errors of the model coefficients are artificially small\n\n$\\Rightarrow$ The p-values are artificially small\n\n$\\Rightarrow$ Could lead to models that are more complex than what is needed\n\n. . .\n\nWe can take overdispersion into account by\n\n-   inflating standard errors by multiplying them by a dispersion factor\n-   using a negative-binomial regression model\n\n# Quasi-Poisson\n\n## Dispersion parameter\n\nThe **dispersion parameter** is represented by $\\phi$ $$\\hat{\\phi} = \\frac{\\sum_{i=1}^{n}(\\text{Pearson residuals})^2}{n - p}$$\n\nwhere $p$ is the number of terms in the model (including the intercept)\n\n. . .\n\n-   If there is no overdispersion $\\hat{\\phi} = 1$\n\n-   If there is overdispersion $\\hat{\\phi} > 1$\n\n## Accounting for dispersion\n\n-   We inflate the standard errors of the coefficient by multiplying the variance by $\\hat{\\phi}$\n\n$$SE_{Q}(\\hat{\\beta}) = \\sqrt{\\hat{\\phi}}  * SE(\\hat{\\beta})$$\n\n\"Q\" stands for **quasi-Poisson**, since this is an ad-hoc solution - The process for model building and model comparison is called **quasilikelihood** (similar to likelihood without exact underlying distributions)\n\n## Quasi-Poisson model {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"2\"}\nhh_age_loc_q <- glm(total ~ age + I(age^2) + location, data = hh_data, \n                family = quasipoisson) \n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term                 | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:--------------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)          |  -0.3843|    0.2166|   -1.7744|  0.0762|  -0.8134|    0.0358|\n|age                  |   0.0704|    0.0082|    8.5665|  0.0000|   0.0544|    0.0866|\n|I(age^2)             |  -0.0007|    0.0001|   -9.2000|  0.0000|  -0.0009|   -0.0006|\n|locationDavaoRegion  |  -0.0194|    0.0640|   -0.3030|  0.7619|  -0.1451|    0.1058|\n|locationIlocosRegion |   0.0610|    0.0626|    0.9735|  0.3304|  -0.0620|    0.1837|\n|locationMetroManila  |   0.0545|    0.0561|    0.9703|  0.3320|  -0.0552|    0.1649|\n|locationVisayas      |   0.1121|    0.0497|    2.2574|  0.0241|   0.0156|    0.2103|\n:::\n:::\n\n\n## Poisson vs. Quasi-Poisson models {.midi}\n\n::: columns\n::: {.column width=\"50%\"}\n<center><b>Poisson</b></center>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term                 | estimate| std.error|\n|:--------------------|--------:|---------:|\n|(Intercept)          |  -0.3843|    0.1821|\n|age                  |   0.0704|    0.0069|\n|I(age^2)             |  -0.0007|    0.0001|\n|locationDavaoRegion  |  -0.0194|    0.0538|\n|locationIlocosRegion |   0.0610|    0.0527|\n|locationMetroManila  |   0.0545|    0.0472|\n|locationVisayas      |   0.1121|    0.0417|\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n<center><b>Quasi-Poisson</b></center>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n| estimate| std.error|\n|--------:|---------:|\n|  -0.3843|    0.2166|\n|   0.0704|    0.0082|\n|  -0.0007|    0.0001|\n|  -0.0194|    0.0640|\n|   0.0610|    0.0626|\n|   0.0545|    0.0561|\n|   0.1121|    0.0497|\n:::\n:::\n\n:::\n:::\n\n## Quasi-Poisson: Inference for coefficients {.midi}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term                 | estimate| std.error|\n|:--------------------|--------:|---------:|\n|(Intercept)          |  -0.3843|    0.2166|\n|age                  |   0.0704|    0.0082|\n|I(age^2)             |  -0.0007|    0.0001|\n|locationDavaoRegion  |  -0.0194|    0.0640|\n|locationIlocosRegion |   0.0610|    0.0626|\n|locationMetroManila  |   0.0545|    0.0561|\n|locationVisayas      |   0.1121|    0.0497|\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n<center><b>Test statistic</b></center>\n\n$$t = \\frac{\\hat{\\beta} - 0}{SE_{Q}(\\hat{\\beta})} \\sim t_{n-p}$$\n:::\n:::\n\n## Quasi-Poisson model {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n   <th style=\"text-align:right;\"> conf.low </th>\n   <th style=\"text-align:right;\"> conf.high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -0.3843 </td>\n   <td style=\"text-align:right;\"> 0.2166 </td>\n   <td style=\"text-align:right;\"> -1.7744 </td>\n   <td style=\"text-align:right;\"> 0.0762 </td>\n   <td style=\"text-align:right;\"> -0.8134 </td>\n   <td style=\"text-align:right;\"> 0.0358 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> age </td>\n   <td style=\"text-align:right;\"> 0.0704 </td>\n   <td style=\"text-align:right;\"> 0.0082 </td>\n   <td style=\"text-align:right;\"> 8.5665 </td>\n   <td style=\"text-align:right;\"> 0.0000 </td>\n   <td style=\"text-align:right;\"> 0.0544 </td>\n   <td style=\"text-align:right;\"> 0.0866 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> I(age^2) </td>\n   <td style=\"text-align:right;\"> -0.0007 </td>\n   <td style=\"text-align:right;\"> 0.0001 </td>\n   <td style=\"text-align:right;\"> -9.2000 </td>\n   <td style=\"text-align:right;\"> 0.0000 </td>\n   <td style=\"text-align:right;\"> -0.0009 </td>\n   <td style=\"text-align:right;\"> -0.0006 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> locationDavaoRegion </td>\n   <td style=\"text-align:right;\"> -0.0194 </td>\n   <td style=\"text-align:right;\"> 0.0640 </td>\n   <td style=\"text-align:right;\"> -0.3030 </td>\n   <td style=\"text-align:right;\"> 0.7619 </td>\n   <td style=\"text-align:right;\"> -0.1451 </td>\n   <td style=\"text-align:right;\"> 0.1058 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> locationIlocosRegion </td>\n   <td style=\"text-align:right;\"> 0.0610 </td>\n   <td style=\"text-align:right;\"> 0.0626 </td>\n   <td style=\"text-align:right;\"> 0.9735 </td>\n   <td style=\"text-align:right;\"> 0.3304 </td>\n   <td style=\"text-align:right;\"> -0.0620 </td>\n   <td style=\"text-align:right;\"> 0.1837 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> locationMetroManila </td>\n   <td style=\"text-align:right;\"> 0.0545 </td>\n   <td style=\"text-align:right;\"> 0.0561 </td>\n   <td style=\"text-align:right;\"> 0.9703 </td>\n   <td style=\"text-align:right;\"> 0.3320 </td>\n   <td style=\"text-align:right;\"> -0.0552 </td>\n   <td style=\"text-align:right;\"> 0.1649 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: #B5BA72 !important;\"> locationVisayas </td>\n   <td style=\"text-align:right;background-color: #B5BA72 !important;\"> 0.1121 </td>\n   <td style=\"text-align:right;background-color: #B5BA72 !important;\"> 0.0497 </td>\n   <td style=\"text-align:right;background-color: #B5BA72 !important;\"> 2.2574 </td>\n   <td style=\"text-align:right;background-color: #B5BA72 !important;\"> 0.0241 </td>\n   <td style=\"text-align:right;background-color: #B5BA72 !important;\"> 0.0156 </td>\n   <td style=\"text-align:right;background-color: #B5BA72 !important;\"> 0.2103 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n# Application exercise\n\n::: appex\n📋 [sta310-sp24.netlify.app/ae/lec-05-overdisp](../ae/lec-05-overdisp)\n:::\n\n# Negative binomial regression model\n\n## Negative binomial regression model {.midi}\n\nAnother approach to handle overdispersion is to use a **negative binomial regression model**\n\n-   This has more flexibility than the quasi-Poisson model, because there is a new parameter in addition to $\\lambda$\n\n<br>\n\n. . .\n\nLet $Y$ be a **negative binomial random variable**, $Y\\sim NegBinom(r, p)$, then\n\n$$\\begin{align}P(Y = y_i) = {y_i + r - 1 \\choose r - 1}(1-p)^{y_i}p^r \\hspace{5mm} y_i = 0, 1, 2, \\ldots, \\infty \\\\\nE(Y) = \\frac{r(1-p)}{p} \\hspace{8mm} SD(Y) = \\sqrt{\\frac{r(1-p)}{p^2}}\\end{align}$$\n\n## Negative binomial regression model {.midi}\n\n::: incremental\n-   **Main idea**: Generate a $\\lambda$ for each observation (household) and generate a count using the Poisson random variable with parameter $\\lambda$\n\n    -   Makes the counts more dispersed than with a single parameter\n\n-   Think of it as a Poisson model such that $\\lambda$ is also random $$\\begin{aligned} &\\text{If }\\hspace{2mm} Y|\\lambda \\sim Poisson(\\lambda)\\\\\n    &\\text{ and } \\lambda \\sim Gamma\\bigg(r, \\frac{1-p}{p}\\bigg)\\\\\n    &\\text{ then } Y \\sim NegBinom(r, p)\\end{aligned}$$\n:::\n\n## Negative binomial regression in R\n\nUse the `glm.nb` function in the **MASS** R package.\n\n<br>\n\n::: callout-caution\nThe **MASS** package has a `select` function that conflicts with the `select` function in **dplyr**. You can avoid this by (1) always loading **tidyverse** after **MASS**, or (2) use `MASS::glm.nb` instead of loading the package.\n:::\n\n## Negative binomial regression in R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhh_age_loc_nb <- MASS::glm.nb(total ~ age + I(age^2) + location, data = hh_data)\ntidy(hh_age_loc_nb) |> \n  kable(digits = 4)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -0.3753 </td>\n   <td style=\"text-align:right;\"> 0.2076 </td>\n   <td style=\"text-align:right;\"> -1.8081 </td>\n   <td style=\"text-align:right;\"> 0.0706 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> age </td>\n   <td style=\"text-align:right;\"> 0.0699 </td>\n   <td style=\"text-align:right;\"> 0.0079 </td>\n   <td style=\"text-align:right;\"> 8.8981 </td>\n   <td style=\"text-align:right;\"> 0.0000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> I(age^2) </td>\n   <td style=\"text-align:right;\"> -0.0007 </td>\n   <td style=\"text-align:right;\"> 0.0001 </td>\n   <td style=\"text-align:right;\"> -9.5756 </td>\n   <td style=\"text-align:right;\"> 0.0000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> locationDavaoRegion </td>\n   <td style=\"text-align:right;\"> -0.0219 </td>\n   <td style=\"text-align:right;\"> 0.0625 </td>\n   <td style=\"text-align:right;\"> -0.3501 </td>\n   <td style=\"text-align:right;\"> 0.7262 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> locationIlocosRegion </td>\n   <td style=\"text-align:right;\"> 0.0577 </td>\n   <td style=\"text-align:right;\"> 0.0615 </td>\n   <td style=\"text-align:right;\"> 0.9391 </td>\n   <td style=\"text-align:right;\"> 0.3477 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> locationMetroManila </td>\n   <td style=\"text-align:right;\"> 0.0562 </td>\n   <td style=\"text-align:right;\"> 0.0551 </td>\n   <td style=\"text-align:right;\"> 1.0213 </td>\n   <td style=\"text-align:right;\"> 0.3071 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> locationVisayas </td>\n   <td style=\"text-align:right;\"> 0.1104 </td>\n   <td style=\"text-align:right;\"> 0.0487 </td>\n   <td style=\"text-align:right;\"> 2.2654 </td>\n   <td style=\"text-align:right;\"> 0.0235 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Negative binomial vs. Quasi-Poisson {.midi}\n\n::: columns\n::: {.column width=\"50%\"}\n<center><b>Quasi-Poisson</b></center>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -0.3843 </td>\n   <td style=\"text-align:right;\"> 0.2166 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> age </td>\n   <td style=\"text-align:right;\"> 0.0704 </td>\n   <td style=\"text-align:right;\"> 0.0082 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> I(age^2) </td>\n   <td style=\"text-align:right;\"> -0.0007 </td>\n   <td style=\"text-align:right;\"> 0.0001 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> locationDavaoRegion </td>\n   <td style=\"text-align:right;\"> -0.0194 </td>\n   <td style=\"text-align:right;\"> 0.0640 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> locationIlocosRegion </td>\n   <td style=\"text-align:right;\"> 0.0610 </td>\n   <td style=\"text-align:right;\"> 0.0626 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> locationMetroManila </td>\n   <td style=\"text-align:right;\"> 0.0545 </td>\n   <td style=\"text-align:right;\"> 0.0561 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> locationVisayas </td>\n   <td style=\"text-align:right;\"> 0.1121 </td>\n   <td style=\"text-align:right;\"> 0.0497 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n<center><b>Negative binomial</b></center>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> -0.3753 </td>\n   <td style=\"text-align:right;\"> 0.2076 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 0.0699 </td>\n   <td style=\"text-align:right;\"> 0.0079 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> -0.0007 </td>\n   <td style=\"text-align:right;\"> 0.0001 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> -0.0219 </td>\n   <td style=\"text-align:right;\"> 0.0625 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 0.0577 </td>\n   <td style=\"text-align:right;\"> 0.0615 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 0.0562 </td>\n   <td style=\"text-align:right;\"> 0.0551 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 0.1104 </td>\n   <td style=\"text-align:right;\"> 0.0487 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n:::\n:::\n\n## References\n",
    "supporting": [
      "05-poisson-pt2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}